### PR TITLE
wasmCloud Incubation Proposal

### PR DESCRIPTION
**Pull request by brooksmtownsend**
Greetings!

This PR contains the proposal for wasmCloud, the CNCF sandbox application runtime, to move to incubation! I've included the best information I could find for the proposal in **proposals/incubation/wasmcloud.md**, and started off our due diligence document to help get all the information in the right places. 

We presented to the Runtime TAG a few months ago and got some great feedback, will link it here in case that's useful: https://youtu.be/j_cUEQttTuw. We most recently participated in the Wasm working group, and we're interested in all things Wasm in the CNCF not just wasmCloud https://youtu.be/cyKC3Rse37Y.

Please let me know if I should provide any additional information in the proposal in this PR, or in the due diligence doc (which is still in progress). We're all very excited for this proposal 🎉

### CODE REVIEW

**Comment by raravena80** [comment]
Following up on this, the wasmCloud team has created the [Incubation DD document](https://docs.google.com/document/d/1MVY2mPqoAbHOGSCKwELS8KwbHkW3v8QS0mMSzHCSi00/edit). 

@rochaporto, @TheFoxAtWork @nikhita can you help with moving the incubation process along?  Thanks! 

cc: @thomastaylor312 @brooksmtownsend @ricochet

**Comment by TheFoxAtWork** [comment]
Quick check here -  wasmCloud is number 6 in the TOC backlog for projects moving levels. We sent out messaging pre-KCCN [regarding changes to the moving levels process](https://lists.cncf.io/g/cncf-toc/message/8570). Now we do need to reconcile this with the current applications in the queue, and each TOC member should be working with the project in doing so, however  given there are[ 5 other projects in the queue ahead of wasmCloud](https://github.com/orgs/cncf/projects/27/views/9), @rochaporto is already assigned to two projects ([OpenCost](https://github.com/cncf/toc/pull/1046) and [OpenYurt](https://github.com/cncf/toc/pull/797)), was there a particular reason for the request to move the incubation process along for this project @raravena80 ?

**Comment by raravena80** [comment]
Thanks for the clarification!

Basically, the wasmCloud maintainers were not aware when or if they needed to start working on the DD doc, or what the timeline was for the TOC to reply with something like: "There are N number of projects ahead in the queue, but you need to complete the DD document by X and hopefully we'll get the process started by Y, etc" (I believe last update was Oct 30, 2023) 

I think the [messaging](https://lists.cncf.io/g/cncf-toc/message/8570) and the [board queue](https://github.com/orgs/cncf/projects/27/views/9) help. 🙏  

The maintainers are aware of the Kubecon freeze, but keep in mind that since this project is directly related to WASM, there may be some urgency with respect to Wasmcon happening June 24-25.

**Comment by thomastaylor312** [comment]
Yeah, we totally understand not wanting to do conference driven @TheFoxAtWork. We don't have any expectations around having it for WasmCon or anything and were just looking for a bit more clarity about timeline/queueing. It is a bit hard to tell from the board where we are at in the queue so it was helpful to know. I did have one question around status. It looks like @mauilion took this on, so should we be in the "Assigned" state now? Also, is there anything we can do in the meantime to make sure everything is ready to go for you folks?

Thank you very much for letting us know the state of the queue and everything, that was extremely helpful!

**Comment by TheFoxAtWork** [comment]
Thats a good question, I have an open ask out to @mauilion to clarify and confirm assignment since this did not follow our documented process.

**Comment by angellk** [comment]
Closing per #1338 - continue there! cc: @mauilion

**Pull request closed without merging**
