### PR TITLE
Porter 2022 Annual Review

### PR DESCRIPTION
**Pull request by carolynvs**
This is [Porter's](https://getporter.org) annual sandbox review for 2022

### CODE REVIEW

**Comment by carolynvs** [comment]
I'm not sure if this feel through the cracks but bumping just in case. 😀

**Comment by amye** [comment]
It did not! We have had some calendar collision to be able to add these to a public meeting. 😄

**Comment by AloisReitbauer** [comment]
This information seems to be quite outdated. Could you please update. Sorry, for the review to take that long

**Comment by mauilion** [comment]
Merging this as it was complete for 2022 and slipped. This project progressed in 2022 and it's great to see that it continues in 2023.

**Pull request merged**
