### PR TITLE
KubeEdge incubation review

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
KubeEdge has been a CNCF Sandbox project since Mar 2019. The project and community keep growing over the last year. We would like KubeEdge to be considered for incubation.

/cc @amye @caniszczyk

### CODE REVIEW

**Comment by alena1108** [comment]
Happy to take on a  Due Diligence for KubeEdge as a TOC

**Comment by dingyin** [comment]
> Happy to take on a Due Diligence for Kubeedge as a TOC

@alena1108 Thank you.

**Comment by raravena80** [comment]
SIG-Runtime presentation link: https://youtu.be/UbbTTHqKilc

**Comment by dingyin** [comment]
SIG-Runtime presentation slides: https://docs.google.com/presentation/d/1k272w_hTCsjwGHY6h1XGJeBMpuV5Cxry2ozyoMDvsPU/edit?usp=sharing

**Comment by alena1108** [comment]
Due Diligence doc draft can be found here: https://docs.google.com/document/d/1GwKZCeXbCnyBkTVwrlUflGSU7lwVgucn2CfkwrCSpsY/edit#.

Note that it's currently going through a SIG review, and not ready for public comments yet

**Comment by alena1108** [comment]
The DD for KubeEdge have been completed. The project solves a complex and unique use case of running containerized applications on the edge devices, which benefits cloud computing ecosystem. Its architecture meets reliability, availability and extensibility criteria needed for further growth and adoption. 

SIG Runtime has provided recommendations to the project owners in the DD doc https://docs.google.com/document/d/1GwKZCeXbCnyBkTVwrlUflGSU7lwVgucn2CfkwrCSpsY/edit#heading=h.kd4eg2uz3lt0. 
On top of it, wanted to prioritize a couple of things to improve:

* Contributors diversity
* Based on several End Users interview feedback, adding edge pod metrics collection support is much needed.

With these two items already prioritized in KubeEdge backlog, I believe the project meets Incubation criteria. Opening the public vote.

**Comment by cantbewong** [comment]
As a co-lead of the Kubernetes IoT Edge Working Group I am adding this non binding comment in support of the KubeEdge application to advance from sandbox to incubation.

I’ve observed active participation of the KubeEdge contributors in the IoT Edge Working Group online meetings and physical conferences. I can attest that they have decent and growing awareness and reputation among vendors, users and prospective users of Kubernetes for edge use cases. The have been valuable citizens in the Kubernetes community during open discussions of how to address challenges of Kubernetes at edge. The analysis in the due diligence document is consistent with my own observations.

On this basis I would encourage voting members of the TOC to approve advance of the KubeEdge project to the incubation level.

**Comment by lizrice** [comment]
Thanks for this DD. I made a couple of comments in the doc - two are small tech queries for my understanding. Please could you also comment on any similar / competing projects (in or outside CNCF) and how KubeEdge differentiates from those?

**Comment by kevin-wangzefeng** [comment]
> Thanks for this DD. I made a couple of comments in the doc - two are small tech queries for my understanding. Please could you also comment on any similar / competing projects (in or outside CNCF) and how KubeEdge differentiates from those?

Thanks @lizrice, I've relied after your comments in the DD doc.

As for differentiation, I don't see any project under CNCF similar / overlapped to what KubeEdge is doing.
In the wider open source eco-system, two major approaches of building edge computing platform with Kubernetes are: 
1. running nodes on the edge
2. running clusters on the edge

KubeEdge started with approach 1; the alternatives choose approach 2, and made some lightweight optimizaions on Kubernetes.

Add what KubeEdge unique to the alternatives for edge computing cases are: 
1. node level autonomy on the edge when disconnected to cloud
2. provided device CRD and device Mapper -- an extensible framework to simplify users integrating iot edge devices with different protocols.

**Comment by dims** [comment]
@kevin-wangzefeng Can you please point me where i can find information on 
- which versions of k8s is supported?
- what features of k8s built-in features are available/not-available?
- Any conformance testing?

thanks,
dims

**Comment by kevin-wangzefeng** [comment]
Thank you Dims, for your speedy review and good questions. Here are the answers and please let us know if you need further clarifications.

> - which versions of k8s is supported?

KubeEdge 1.3 supports Kubernetes 1.17, and 1.18 is going to be supported by KubeEdge 1.4.
Full compatibilities can be found here: https://github.com/kubeedge/kubeedge#kubernetes-compatibility.

> - what features of k8s built-in features are available/not-available?

KubeEdge extends native containerized application orchestration capabilities to nodes on the edge. KubeEdge is built based on Kubernetes to provide infrastructure support for network, application deployment and metadata synchronization between cloud and edge.
One major difference of running applications on the edge comparing to running applications on the cloud is the pod network, since there's no CNI plugin providing communication capabilities between cloud and multiple edge private networks. The KubeEdge community is having discussions to develop cross private network communication support for advanced use cases.

> - Any conformance testing?

KubeEdge community is currently defining a set of end-to-end tests to verify various functionalities of edge computing. We currently don't run Kubernetes conformance test due to the difference and limitation of underlying network environment as mentioned above. If you have any suggestion on additional tests needed, we can certainly discuss with the KubeEdge community and add it to future plans.

**Comment by dims** [comment]
@kevin-wangzefeng thanks a ton! sounds good.

**Comment by caniszczyk** [comment]
https://www.cncf.io/blog/2020/09/16/toc-approves-kubeedge-as-incubating-project/

**Pull request merged**
