### PR TITLE
Dragonfly Incubating Stage Review

### PR DESCRIPTION
**Pull request by allencloud**
Dragonfly has been a CNCF sandbox project since October 2018. After that, Dragonfly community got lots of help from the foundation. Now it has shown the healthy growth and cloud native adoption.

After talking with @caniszczyk, we felt it was time to propose Dragonfly for the incubation level. This pull request describes the current status of Dragonfly. And Dragonfly community wishes to hear more feedback from the ecosystem. Thanks. 

Signed-off-by: Allen Sun <allensun.shl@alibaba-inc.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
RFC @cncf/toc

**Comment by caniszczyk** [comment]
What was the progress of Dragonfly being rewritten in golang from Java? It looks like it’s mostly done? https://github.com/dragonflyoss/Dragonfly/issues/346

**Comment by allencloud** [comment]
> What was the progress of Dragonfly being rewritten in golang from Java? It looks like it’s mostly done? dragonflyoss/Dragonfly#346

Yes, We have finished that in 0.4.0 version. Currently Dragonfly is totally written in Golang.  Now latest version of dragonfly is 0.4.3. We will release 0.5.x to add more essential features from the community. And in about October, we will launch the GA version of 1.0.0.

**Comment by fanux** [comment]
We using dragonfly to distribute large AI resource files to cluster nodes. We hope that dragonfly enters the incubation stage.

**Comment by allencloud** [comment]
Here is a link for Dragonfly Due Diligence Draft: https://docs.google.com/document/d/1FauIs9BXRCioUCYPdO9gfy1uiPw9ESKRu0s4bgd5Dgw/edit#
We do appreciate any review for draft from the community as a sign of support. ❤️ 🕊 🚢

**Comment by chira001** [comment]
The CNCF SIG Storage has completed a review of Dragonfly.

The project presented to us August 28th this year: https://www.youtube.com/watch?v=Sl7ZDt7rx4M

We had some questions which were captured by the project here: https://github.com/dragonflyoss/community/blob/master/meetings/cncf-sig-storage-feedback.md

I completed a basic test deployment in a test environment covering basic functionality and failover scenarios and, in general, Dragonfly appears to be simple to deploy and a focus on low overhead.   Failover and operational maintenance seemed straightforward and operations like image pulls could complete even while some nodes where in a failed state.

We had some further queries that were captured by the team and detailed responses are included here: 
https://github.com/dragonflyoss/Dragonfly/issues/1205
https://github.com/dragonflyoss/Dragonfly/issues/1204

The CNCF SIG Storage raised this on the agenda for 12th February and recommend move to incubation.

**Comment by caniszczyk** [comment]
Thanks @amye can you kick off the vote tomorrow?

**Comment by amye** [comment]
Waiting on a TOC member to sponsor, will coordinate with.

**Comment by allencloud** [comment]
> Thanks @amye can you kick off the vote tomorrow?

@caniszczyk Sig Storage and @chira001 made a very detailed review for Dragonfly. While I am afraid that we still need a TOC sponsor and Due Diligence which is requested in the cncf-toc channel https://lists.cncf.io/g/cncf-toc/topic/67574577#3930. 

/cc @amye

**Comment by sheng-liang** [comment]
I’m happy to do it (sponsor and run the due diligence.)

Sheng

**Comment by allencloud** [comment]
> I’m happy to do it (sponsor and run the due diligence.)

@sheng-liang any update with the due diligence?
Please feel free to tell me if I could help anything. Thx.

**Comment by sheng-liang** [comment]
@allencloud I'm working through the documents. I will need your help connecting me with a few users and committers. I will talk to them, then summarize and post my findings publicly. I hope to verify that Dragonfly 1) is used in production by 3 end users 2) has a healthy number of committers.

**Comment by amye** [comment]
Hey @sheng-liang, checking in here on status. Thanks!

**Comment by sheng-liang** [comment]
I'm done with reviewing the project and the due-diligence. The due-diligence Google doc has been updated. What's the next step?

**Comment by allencloud** [comment]
Thanks for your great work. @sheng-liang 
With the due-diligence done, I think the next step is to kick the incubation vote. /cc @amye @caniszczyk

**Comment by amye** [comment]
Yes, @sheng-liang should call for a formal vote, here is fine.

**Comment by sheng-liang** [comment]
I have reviewed the project and the due diligence doc. I have talked to a number of Dragonfly end users and committers and have verified that: 1) Dragonfly is used in production by 3 end users listed in due diligence doc and 2) Dragonfly has a healthy number of committers. My feedback has been incorporated into the due diligence doc. I believe the Dragonfly project is ready for entering incubation. I'd like to call for a TOC vote.

**Comment by amye** [comment]
Thank you, I will post the vote to @cncf/toc!

**Comment by caniszczyk** [comment]
Welcome to the CNCF incubator :) 

https://www.cncf.io/blog/2020/04/09/toc-votes-to-move-dragonfly-into-cncf-incubator/

**Comment by caniszczyk** [comment]
votes: https://lists.cncf.io/g/cncf-toc/message/4517

**Pull request merged**
