### PR TITLE
Project on-boarding Flowchart

### PR DESCRIPTION
**Pull request by ultrasaurus**
This PR has two commits
1) move [original flowchart](https://docs.google.com/drawings/d/1Nvq188i3LGoWgtu1Jdk0wmpOcB6ZxvAc8_ppPygbnus/edit) into mermaid markdown
2) alternate flowchart to match observed or what seems to be the emerging process

Not wed to any of these ideas, just attempting to provide a little structure to clarify

image

### CODE REVIEW

**Comment by ultrasaurus** [comment]
Note:  I see the labels are getting cropped.  If this seems like a good approach to people, I can look into fixing formatting.

**Comment by ultrasaurus** [comment]
related to https://github.com/cncf/toc/issues/248

**Comment by michelleN** [comment]
Thanks @ultrasaurus for putting this together. It really got me thinking about how to track this work and split it into stages. The TOC used your flowchart in one of the meetings so I just wanted to tell you how much I appreciate it.

I was thinking perhaps we could split the process into stages:

1. **Initial phase** -- project maintainers open up an issue to propose their project. They'd fill out a lightweight issue template outlining a short (max 2 paragraph) description of project, history, and problem it solves, statement on alignment with CNCF, and preferred project level (optional)
2. **Triage phase** -- this is where a TOC member will take a quick look at the project. If the project does not align with the CNCF, they will respond to the issue with a justification of why it does not fit. If it does align, then they will tag the chairs of the relevant SIG and request a _**recommendation**_
3. **SIG Presentation phase** -- the project will schedule a presentation with the SIG and open a pull request with the project proposal. The SIG will discuss the project and make a recommendation by filling out a _recommendation template_. This template will have the following questions: Is this project a good fit for the CNCF? If so, why? Recommended project level? Any concerns or notes the TOC should keep track of?
4. **TOC Action phase** -- If the project is turned away, someone from the TOC will gather information and respond on the issue. If the project is recommended for sandbox, the TOC will discuss the project on a call after watching a recording of the presentation before the meeting, ask questions and then ask for 3 sponsors. If the project is recommended for incubating, the TOC will find 2 sponsors and then work with the SIG on DD and user interviews and come back for a vote.

We discussed this new triage phase on a call last week, so I added that here. Do we think that the phases make the process more clear?

**Comment by ultrasaurus** [comment]
is recommendation template same as [Due Diligence template](https://github.com/cncf/toc/blob/master/process/dd-review-template.md) ?

**Comment by jbeda** [comment]
Some notes from the TOC meeting on 12/17.

Wrt the triage phase, it is likely that the TOC member that does the triage would make an initial call. If the answer is no they would socialize that via lazy consensus with the rest of the TOC over email and give other members a chance to argue the yes case.  We could also look at putting in a more official appeals process.

We would also want some guidance on when/how projects can re-apply.

Finally, I remember the triage phase being "turn based" vs. "time based" wrt which TOC member gets assigned.

Overall goal here is to get to a quicker answers for projects so that they aren't left hanging.  We also want to be able to leverage the SIGs more effectively to improve project evaluation throughput.

**Comment by lizrice** [comment]
Someone smart (@mattfarina I think) suggested using the same template for initial submission and annual reviews so that we can easily diff the two. I’ve just raised #327 for the annual review process. There would be some things that are N/A for a new project (e.g. No devstats page yet) but I think it’s doable.

**Comment by lizrice** [comment]
+1 for “turn-based” triage responsibility for TOC members

**Comment by xiang90** [comment]
@michelleN I think the overall process makes sense. The phases are clear. One suggestion is to add expected timelines for each phase.


> Wrt the triage phase, it is likely that the TOC member that does the triage would make an initial call. If the answer is no they would socialize that via lazy consensus with the rest of the TOC over email and give other members a chance to argue the yes case. We could also look at putting in a more official appeals process.

@jbeda @lizrice 

For the triage phase, shall we make it less restrict? Instead of `turn-based` or `time-based` to assign TOC member, we can make it slot based and first-pick-first-occupy for all TOC members to act concurrently. For example, we make X slot every two weeks and any TOC member can pick projects from the triage pool.

**Comment by lizrice** [comment]
I've had a first pass at a flowchart reflecting the phases Michelle suggested, also incorporating a stab at the timeframes. Comments welcome.  

I don't know why Mermaid has laid it out so badly or truncated some labels, but if you start in the middle with **New Project proposal** I hope it makes some sense. We would certainly need a clearer layout before publishing! 

Onboarding flowchart

[1] A project wishing to join the CNCF first raises an issue in GitHub using the proposal issue template _(Creating this template is still TODO)_

[2] A TOC member performs an initial triage on this issue:

* TOC member assigns issue to themselves during triage
* TOC member might reach out to project maintainers with questions
* If the TOC member is leaning towards rejecting the project, they will discuss it with other TOC members first before responding
* To request a SIG recommendation, the TOC member assigns issue to the relevant SIG chairs

[3] SIG Chairs co-ordinate with the project maintainers to agree presentation date and answer questions about what is required in this presentation

[4] SIG discusses with project maintainers and once they have done their assessment, SIG completes a recommendation template _(TODO recommendation template)_

[5] TOC members review and discuss the recommendation, and agree the next step by lazy consensus. Note that the TOC are not required to accept the recommendation. 

[6] Sandbox requires sponsors from the TOC members. Sponsors should have a reasonable belief that the project is on a good path towards incubation. If insufficient members step forward as sponsors within the timeframe, then the proposal is rejected.

[7] [Due Diligence](https://github.com/cncf/toc/blob/master/process/due-diligence-guidelines.md) is performed when a Project wants to join or move to Incubation level. The Due Diligence document should also be updated for a Graduation proposal.

[8] For incubation and graduation the TOC vote taking into account the [requirements](https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc). Projects get accepted via a 2/3 supermajority vote of the TOC.

**Comment by leecalcote** [comment]
Use of the term "Due Diligence" is a point of confusion for some.

Casually speaking, starting with Sandbox projects undergo due diligence. Strictly speaking, "due diligence" is a set of specific criteria projects undergo as entrance requirements to Incubation.

It may behoove us to choose a non-generic term for the Incubation stage DD, so as to avoid misunderstanding with those performing and those receiving due diligence.

**Comment by xiang90** [comment]
@leecalcote 

> Use of the term "Due Diligence" is a point of confusion for some.

With the SIG structure, there are three output documentations:

1. project proposals. This is what the project maintainers should prepare. There is already a template.

2. SIG recommendation. This is what the SIG should prepare. There is no cross SIG template yet.

3. DD documentation (only need for incubation and graduate). This is what the TOC should drive and SIG+Project maintainers should co-prepare together. There is a template. 

> Alternatively, it may help to refer to the diligence that Sandbox proposals receive as "pre-DD".

As @chira001 mentioned in today's meeting, SIG could collect informations about the sandbox project for analysis/recommendation and future use for the incubation DD. We can keep this information collection doc somewhere. But it is not required by the process as any intermediate output for the next stage.

**Comment by lizrice** [comment]
Latest version of proposed process is [here](https://docs.google.com/presentation/d/1xQHPHI7U2WxIUJm5zSj1MamWNr-Ru7_4nABrRkveDBU/edit?usp=sharing). (Will need reformatting into MD/asciidoc once we are happy with the gist of it).

**Comment by lizrice** [comment]
Please see #355

**Comment by lizrice** [comment]
Closing now that we have #355 merged

**Pull request closed without merging**
