### PR TITLE
Falco Graduation Proposal

### PR DESCRIPTION
**Pull request by leogr**
Hello TOC and CNCF community 👋,

With this PR we are proposing Falco for CNCF graduation.

# **What is Falco?**

Falco is a threat detection engine providing runtime security alerting for containerized applications and the cloud.

# **Why we are ready to graduate**

Falco joined the CNCF as a sandbox project in 2018-10-10 and evolved into incubation on 2020-01-08. The community believes the next natural step is for Falco to apply for graduation. The project has reached  maturity in community health, diversity of contributions & contributors, and ecosystem adoption.

Falco currently stands with **5,300+ GitHub stars** and **165+ contributors across the various repos** in the [**falcosecurity**](https://github.com/falcosecurity) GitHub organization. The community has also expanded their footprint to **1,695 users** registered in the [**Falco community Slack**](https://kubernetes.slack.com/messages/falco). 

Falco’s adoption has grown widespread within the Kubernetes ecosystem; users of the project include **AWS, Qonto, and Shopify, + others**. The project has been integrated into a variety of derivative products such as **R6/Phoenix, Giant Swarm/Falco App, gVisor, StackRox, Tarian, Sysdig Secure, + more**.

The project [maintainers](https://github.com/falcosecurity/evolution/blob/main/MAINTAINERS.md) believe that Falco meets the requirements for graduation status.

# **How you can help today**

* If you are a fan of Falco, we would love a 👍, ❤️, or 🚀 on this PR.
* If you are using Falco in production, please add your name to our [ADOPTERS.md](https://github.com/falcosecurity/falco/blob/master/ADOPTERS.md) doc.
* If you do any of the above, share it on the social media platform of your choice.

With ❤️ on behalf of the Falco community!

### CODE REVIEW

**Comment by TheFoxAtWork** [comment]
Hello!  Justin and I are the TOC sponsors for Falco’s graduation.  We are requesting the project refresh their due diligence doc: https://docs.google.com/document/d/1TJCzW8dQ6858lw2UNY-H5LMnvEd4GzwjuOcDInimeyA/edit#heading=h.378jkvcve1nq to be:

1. comprehensive,
2. updated with the current state of the project leveraging the updated DD template (https://github.com/cncf/toc/blob/main/process/dd-review-template.md), and
3. cover the graduation exit criteria.

We also ask that your provide 5-7 potential adopters for interviews as part of this process. please reach out with questions!

**Comment by leogr** [comment]
Hello!

Quick update:

The second security audit (performed by the firm Quarkslab) was completed in Jan 2023, so I've [updated the proposal document](https://github.com/cncf/toc/pull/956/commits/6665302fd52a7777090e7874c5f5c9cc97ffe103) accordingly. We will also report this update in the DD doc shortly.

Thanks

**Comment by TheFoxAtWork** [comment]
Providing a brief update here: @justincormack and I met with the project to go over the Due Diligence and explore some areas of focus for the project to undertake prior to Graduation Public Comment opening. The details of the proposed path are defined here: https://docs.google.com/document/d/12l65c6qC91akgFjzw7BM3KdNJAa5LyDG17sdpdfwf3g/edit?usp=sharing and the project has made signifiant progress on several areas.

**Comment by leogr** [comment]
> Providing a brief update here: @justincormack and I met with the project to go over the Due Diligence and explore some areas of focus for the project to undertake prior to Graduation Public Comment opening. The details of the proposed path are defined here: https://docs.google.com/document/d/12l65c6qC91akgFjzw7BM3KdNJAa5LyDG17sdpdfwf3g/edit?usp=sharing and the project has made signifiant progress on several areas.

We've created a [Progress Tracker](https://github.com/falcosecurity/evolution/issues/281) for our ongoing tasks related to those focus areas. We hope it's helpful to you.

Thanks :pray:

**Comment by TheFoxAtWork** [comment]
Here is the corrected Graduation Due Diligence document

https://docs.google.com/document/d/1Hkwp4qMoazqVhrODmJwDitvBI4chbsg0OBLQhRGmW3c/edit?usp=drivesdk

**Comment by lizrice** [comment]
I kinda hate to bring this up but doesn’t Falco use kernel modules? These weren’t included as part of the GPL-2.0 exception recently granted for eBPF programs, so I’m curious whether the license checks are fully complete

**Comment by lizrice** [comment]
I can't explain why they didn't come up in the license scan, but there are a whole bunch of C files clearly dual-licensed GPLv2 / MIT in [this directory](https://github.com/falcosecurity/libs/tree/master/driver), with the following header: 

```
This file is dual licensed under either the MIT or GPL 2. See MIT.txt or GPL2.txt for full copies of the license.
```
This is consistent with the comment @leogr made about [needing a license exception for kernel modules as well as eBPF](https://github.com/cncf/foundation/issues/474#issuecomment-1664126682). I think that license exception is a reasonable request, but if we had to have GB blessing before the TOC could approve eBPF projects for graduation, it would make sense that it's also required for kernel modules, no?

**Comment by leogr** [comment]
:clap: 

:heart_eyes:

**Pull request merged**
