### PR TITLE
feat(docs): add Persian translation for DEFINITION.md

### PR DESCRIPTION
**Pull request by molavi25**
Added a Persian translation of the DEFINITION.md file to improve accessibility and inclusivity for Persian-speaking contributors and users. This translation covers the key sections including Definition, Criteria, Process, and Conclusion.

- Translated the project definition and criteria for inclusion of new projects into CNCF.
- Detailed the process of proposal submission, TOC review, community feedback, and TOC decision.
- Ensured alignment with CNCF’s mission and standards.

This contribution aims to foster a more diverse and inclusive community by providing documentation in multiple languages.

### CODE REVIEW

**Comment by riaankleinhans** [comment]
@molavi25 thank you for the contribution. We want to make the CNCF's work accessible to as many communities as possible.

The DEFINITION.md is the home of the official "CNCF Cloud Native Definition" captured in the first 3 paragraphs in English.

All the translations in the document is localized translations of those 3 paragraphs.
It would be great if you could updated the PR to only add the Persian translating of the "CNCF Cloud Native Definition" 

About the content that you submitted, can please point me to the document you translated, that would help me determine how we can include that in the repo with another PR.
 
Lastly, please note all commits to the repo must be signed. Instructions [here](https://github.com/cncf/toc/pull/1384/checks?check_run_id=28119238340).

**Review by angellk — APPROVED** [review]
lgtm - thanks for contributing the Persian translation @molavi25

**Comment by angellk** [comment]
@molavi25 please fix the DCO and this can be merged

**Comment by angellk** [comment]
@molavi25 please re-open if you would still like to contribute this Persian translation along with the suggestions from @riaankleinhans

**Pull request closed without merging**
