### PR TITLE
Propose LitmusChaos as a CNCF SandBox project

### PR DESCRIPTION
**Pull request by umamukkara**
Hi,

This is PR corresponding to the issue #390 .

### CODE REVIEW

**Comment by michelleN** [comment]
This was presented in SIG App Delivery today. @bryanl is working with the maintainers on gathering more info and putting together a recommendation.

**Comment by k8s-dev** [comment]
Dropping by to say that I had attended SIG app delivery session the other day, eagerly looking forward to see LitmusChaos to be accepted as CNCF sandbox project.

**Comment by AloisReitbauer** [comment]
SIG Review Notes: https://docs.google.com/document/d/10G1fOySiYeCYIkWhz_ueyXTBi04_pQVRkDBdt2ryCFo/edit#

**Comment by umamukkara** [comment]
Thank you @AloisReitbauer. @amye  , can you please suggest the next steps?

**Comment by caniszczyk** [comment]
LitmusChaos was accepted into the sandbox:
https://lists.cncf.io/g/cncf-toc/message/4853

project onboarding will happen here https://github.com/cncf/toc/issues/468

**Pull request merged**
