### PR TITLE
Cortex 2020 Annual Review

### PR DESCRIPTION
**Pull request by gouthamve**
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

### CODE REVIEW

**Comment by amye** [comment]
@cncf/toc - we have our first annual review in! Any questions?

**Comment by quinton-hoole** [comment]
Is this a self-review by the Cortex team?

I think it would be useful for the newly-formed cncf-sig-observability to take a look and comment.

cc @halcyondude @raravena80

**Comment by sheng-liang** [comment]
Agreed @quinton-hoole . SIG observability please take a look.

**Comment by amye** [comment]
No, removing SIG-Observability per [Annual Review documentation](https://github.com/cncf/toc/blob/master/process/sandbox-annual-review.md): 

The outcome of the annual review is either:

At least three (two before the TOC grows to 11 members) TOC members agree to continue to sponsor the project in Sandbox, or
If enough TOC members don’t agree to continue to sponsor the project, we will discuss archiving or other next steps with you.
Additionally, the TOC might recommend that you apply for Incubation stage. This requires extra work and due diligence so it’s not a possible outcome directly from this lightweight annual review.

--- 
SIGs do not need to review annual reviews, this is TOC only.

**Comment by alena1108** [comment]
LGTM for Sandbox Annual Review

**Comment by gouthamve** [comment]
Hi @amye and @alena1108 for the update! I am a little confused about the last update, does this mean the TOC has completed the annual review for Cortex?

Does the TOC has any feedback? Is there anything we could do as a team to help?

Thanks,
Goutham.

**Comment by alena1108** [comment]
@gouthamve per https://github.com/cncf/toc/blob/415a62d03547a6008a222ed194ecd0530fe53d1a/process/sandbox-annual-review.md#review-outcomes, 3 TOC members should agree to support the project by putting LGTM to PR. I was the first one, 2 more votes are needed. 

I wanted to highlight 3 things done well:

1. Documentation https://cortexmetrics.io. - easy to follow and navigate.
2. Release management. A couple of things that can be improved in Release Notes documentation, to make it more concise and easy to read:

* Would make sense to move `Config file breaking changes` to its own separate document. And in general avoid putting too much detail to the release notes. Just a short bug description is enough, the details can be listed in the corresponding bug. This way it's a bit easier to read, and understand the release scope.

* Group enhancements/feature/change and Bug fixes in separate categories to avoid [FEATURE]/[BUG FIX] prefixes

3. Section on comparison with Thanos is very useful.

Note that the project's request for incubation will be reviewed separately.

**Comment by RichiH** [comment]
As a data point, SIG o11y accepted the DD documentation and will suggest moving Cortex to incubation stage: https://github.com/cncf/toc/pull/315#issuecomment-634162078

**Comment by lizrice** [comment]
Also LGTM for Sandbox Annual Review

**Comment by kgamanji** [comment]
LGTM for annual review

**Pull request merged**
