### PR TITLE
Meshery 2023 Annual Review

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

### CODE REVIEW

**Comment by craigbox** [comment]
I'm happy to have a go at this one.

**Comment by Aisuko** [comment]
Hi, Guys. Here is the PR https://github.com/cncf/landscape/pull/3545

**Comment by craigbox** [comment]
(Because the TAG Network chair is the person who submitted this review, I submitted my comments directly to the TOC liaisons.)

**Review by mattfarina — APPROVED** [review]
Thanks for submitting the annual review. I have the following feedback for you:

- On the Meshery website the CNCF logo is used instead of the Sandbox specific logo. Can you please update to use the sandbox logo. I filed an issue for it at https://github.com/meshery/meshery.io/issues/1513.
- You bring up a possible collaboration with Artifact Hub. I would suggest you reach out to the project either in Slack or by [filing an issue with the project](https://github.com/artifacthub/hub/issues).
- In response to, "We could use the TOC's assistance in encouraging other CNCF projects to represent their deployment best practices in the Meshery Catalog.", the TOC does not currently have the time or means to encourage projects in this manner. I would suggest 2 alternatives...
  - Contact TAG Networking about this
  - Reach out to other CNCF projects and request that they do this. It would help them with awareness and marketing, in addition to sharing best practices to do this.
- The review references SMI which is now an archived project and was mostly inactive prior to that. This reference should be avoided in the future.
- As per your assessment that Meshery is ready to move to Incubation, from a quick look it appears you are in a state to file for Incubation and to begin that process.

Thank you for the thorough review. I look forward to the incubation request.

**Pull request merged**
