### PR TITLE
Emissary-ingress proposal for CNCF Incubation

### PR DESCRIPTION
**Pull request by danielbryantuk**
This is a proposal for the Ambassador API Gateway to be included as a CNCF Incubation project.

We've discussed the project with several CNCF TOC members, but have not scheduled it for a TOC meeting yet.

Please let us know if anyone has any feedback or questions.

Best wishes,

### CODE REVIEW

**Comment by caniszczyk** [comment]
Thanks @danielbryantuk, this should also go through SIG Network for a due diligence review.

Awesome though, thanks for the project proposal.

**Comment by lizrice** [comment]
@mattklein123 the related email from @danielbryantuk says you have volunteered to drive the DD process, can you confirm please here for the record?

**Comment by mattklein123** [comment]
Confirmed. cc @leecalcote

**Comment by jonathanmccracken** [comment]
yes please! I have been using Ambassador for years with Kubernetes and it is a great way to get microservices leveraging Envoy in many different use-cases.
+1

**Comment by amye** [comment]
@danielbryantuk: SIG Network would like to put you on the May 21st meeting. Is your team ready to present? 
@leecalcote  for visibility

**Comment by danielbryantuk** [comment]
Hi @amye, apologies but this is too short notice at the moment (being based in the UK time zone, I've only just seen the message today). Could we reschedule to another upcoming SIG meeting, please? Anytime from next week should work.

**Comment by amye** [comment]
Of course! Let's put you in for June 4th, if that works for you.

**Comment by danielbryantuk** [comment]
Thanks, @amye, this sounds great! Is there any material/guidance we should consult before presenting?

**Comment by leecalcote** [comment]
@danielbryantuk, I'll shoot you an email.

**Comment by danielbryantuk** [comment]
Cheers, @leecalcote -- much appreciated!

**Comment by ksummersill2** [comment]
Love Ambassador. Please push forward with CNCF!

**Comment by danielbryantuk** [comment]
Hey @leecalcote, I hope all is good with you and family! Just wanted to follow up with you, as I haven't seen an email yet? I was keen to check I haven't missed this, or it hasn't been spammed etc, as our scheduled presentation slot is only a week away :)

**Comment by danielbryantuk** [comment]
Hi @leecalcote, just a subtle nudge asking if have you sent the email, please?

We're keen to make sure that the content shared will be the most useful it can, and we're only ~3 days away from the presentation now.

I hope all is well!

**Comment by amye** [comment]
[Kuma](https://docs.google.com/presentation/d/1zbeFCR2JBuQWH0XIfYmGpoFerv2fg8Wr7ncHSso860A/edit#slide=id.p) had a very good presentation at the last SIG meeting, if you're looking for examples!

**Comment by danielbryantuk** [comment]
Many thanks, @amye -- we'll take a look :)

**Comment by danielbryantuk** [comment]
Thanks again, @amye, this was definitely a useful resource. In regards to the presentation, I was just looking on the SIG Networking GitHub page, but wasn't exactly sure which meeting we should be joining on Thursday -- is there a calendar invite/Zoom link etc, please?

**Comment by amye** [comment]
https://www.cncf.io/community/calendar/ has the updated schedule, but you're looking for 11am Pacific on Thursday, June 4th. 
Ping me privately and I'll invite you to the meeting directly.

**Comment by danielbryantuk** [comment]
That's super helpful, thanks @amye! Just to explain my confusion (so others don't make the same mistake :) ), Googling "sig network" led me here: https://github.com/kubernetes/community/tree/master/sig-network

And I couldn't see a mention of us on the upcoming SIG Networking Meeting linked from this GitHub repo

**Comment by amye** [comment]
@mattklein123: checking in on DD status? Thanks!

**Comment by danielbryantuk** [comment]
Hi @amye, @mattklein123, @leecalcote, and everyone, apologies for the delay (lots of preparation for KubeCon EU :) ). We've completed our first draft of the due diligence document and made this publicly accessible here: https://docs.google.com/document/d/1bJhfqEADNI7YSQPyi8Kmb1VvN2FaqxMFRsYvp-vZQLg/edit?usp=sharing

We welcome comments and feedback, and please reach out with any questions

**Comment by danielbryantuk** [comment]
Hi @amye, I hope all is good! I was keen to check if there were any updates or questions related to the DD doc we shared last month?

**Comment by amye** [comment]
@danielbryantuk, check with @mattklein123 for his review, he's the one that needs to review and call for public comment.

**Comment by mattklein123** [comment]
Sorry I didn't realize the ball is in my court here. I will take a look.

**Comment by mattklein123** [comment]
Sorry for the long delay here. I just looked through the DD doc and left a few comments, otherwise it LGTM and I think the project meets the incubation bar and is aligned with the CNCF mission. @leecalcote do you have any comments on the SIG networking side?

**Comment by danielbryantuk** [comment]
Hey @leecalcote, I hope all is good! As per comments in the doc, I plan to update the doc/PR with the new project name as soon as folks have shared their feedback. Is there anything outstanding from your (SIG Networking) perspective?

**Comment by leecalcote** [comment]
Green lights across the board from SIG Network. 🟢

**Comment by danielbryantuk** [comment]
Happy new year to everybody -- this is awesome news! Many thanks, @leecalcote 🙇 

Hi @amye, can I ask what the next steps are now, please?

**Comment by amye** [comment]
@mattklein123 will call for public comment on the TOC list per yesterday's TOC call, thanks!

**Comment by caniszczyk** [comment]
FYI we have agreed that the new name of the project is 'emissary-ingress' and will live here https://github.com/emissary-ingress - we also secured legal clearance on the name so we're all good, also @mattklein123 the original sponsor here is aware.

@amye I believe we are safe to move to a public TOC vote now

**Comment by danielbryantuk** [comment]
@ everyone -- the TOC vote is now open on the mailing list. Non-binding community votes would be most appreciated! https://lists.cncf.io/g/cncf-toc/message/5715

Many thanks for kicking off the process @caniszczyk and @amye !

**Comment by amye** [comment]
Editing with new name for clarity

**Comment by caniszczyk** [comment]
The Emissary-ingress project has been approved for incubation. 
https://lists.cncf.io/g/cncf-toc/message/5715

9/11 -- passes
+1 B  
Liz Rice: https://lists.cncf.io/g/cncf-toc/message/5744
Justin Cormack: https://lists.cncf.io/g/cncf-toc/message/5715
Sheng Liang: https://lists.cncf.io/g/cncf-toc/message/5752
Dave Zolotusky: https://lists.cncf.io/g/cncf-toc/message/5754
Richardo Rocha: https://lists.cncf.io/g/cncf-toc/message/5755
Lei Zhang: https://lists.cncf.io/g/cncf-toc/message/5756
Alena Prokharchyk: https://lists.cncf.io/g/cncf-toc/message/5715
Davanum Srinivas: https://lists.cncf.io/g/cncf-toc/message/5791
Erin Boyd: https://lists.cncf.io/g/cncf-toc/message/5792

**Pull request merged**
