### PR TITLE
Update TAG Environmental Sustainability charter document

### PR DESCRIPTION
**Pull request by guidemetothemoon**
Added minor modifications to the TAG Environmental Sustainability charter document according to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-charter.md)

Related to https://github.com/cncf/tag-env-sustainability/issues/457

### CODE REVIEW

**Review by leonardpahlke — APPROVED** [review]
LGTM

**Comment by leonardpahlke** [comment]
PTAL @angellk || @kevin-wangzefeng || @TheFoxAtWork

**Review by TheFoxAtWork — APPROVED** [review]
LGTM

**Comment by leonardpahlke** [comment]
PR is ready to get merged @mrbobbytables @jeefy

**Comment by guidemetothemoon** [comment]
@mrbobbytables @jeefy a gentle reminder about merging this PR so that we can finalize https://github.com/cncf/tag-env-sustainability/issues/457

Thanks! 🙌

**Review by TheFoxAtWork — APPROVED** [review]

**Comment by TheFoxAtWork** [comment]
Merging, this is a known change for some time.

**Pull request merged**
