### PR TITLE
Fix SIG charter issue and amended chairs names

### PR DESCRIPTION
**Pull request by resouer**
It is reported the current charter has format issue which "looks weird". Seems to be the extra blank lines issue.

Also, amended the chairs names in the charter.

### CODE REVIEW

**Comment by resouer** [comment]
Kindly ping @caniszczyk , due to unknown permission issue we can't get this merge.

Could u or anyone else review it and merge? 🥇

**Comment by ultrasaurus** [comment]
propose that we remove SIG chair names from this doc and keep them in one place in [sigs/README](https://github.com/cncf/toc/blob/master/sigs/README.md)

**Comment by idvoretskyi** [comment]
cc @amye

**Comment by amye** [comment]
We'll do both, people tend to have questions and look in both places.

**Pull request merged**
