### PR TITLE
Add Keylime as a CNCF Sandbox Proposal

### PR DESCRIPTION
**Pull request by lukehinds**
This PR contains a proposal to add [Keylime](https://keylime.dev) to the CNCF as a Sandbox project.

Keylime is a highly scalable remote boot attestation and runtime integrity measurement solution. Keylime enables users to monitor remote nodes using a hardware based cryptographic root of trust. It was designed and developed to operate in a cloud native environment. Keylime was originally born out of the security research team in MIT. It is now an open source project with its own diverse and active community.

### CODE REVIEW

**Comment by resouer** [comment]
@amye Is proposal still required for new CNCF Sandbox process?

**Comment by amye** [comment]
I do need to have something to merge into the repo, so yes :)

**Comment by erinaboyd** [comment]
@amye is this being considered in the next round of sandbox reviews?

**Comment by amye** [comment]
The next round of sandbox reviews is September 8th, next Tuesday.

**Comment by amye** [comment]
https://docs.google.com/spreadsheets/d/1Nnh_usr0tSZxaUpxTusqeIqKxMmvuEViRkyO9e_Do40/edit?usp=forms_web_b#gid=1398510353 has the projects that have submitted.

**Comment by amye** [comment]
This project will be reviewed in the next closed TOC meeting, September 22nd.

**Pull request merged**
