### PR TITLE
2020 KubeEdge Annual Review

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
Annual review for KubeEdge

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Thanks @kevin-wangzefeng , this is very useful.

May I suggest that you do a brief presentation to CNCF-SIG-Runtime to help spread awareness, and give the community an opportunity to understand the status of the project, and ask questions of the team.

@raravena80 Can get you added to the agenda.

**Comment by raravena80** [comment]
@kevin-wangzefeng happy to schedule a presentation. Feel free to add it to any of the upcoming SIG-Runtime meetings or let us know what works: https://bit.ly/cncf-sig-runtime-meeting-notes. Thanks.

**Comment by amye** [comment]
@quinton-hoole: this isn't required for an annual review. 
However, KubeEdge indicates that they're preparing for an incubation review, we should wait until that proposal is available.

**Comment by kevin-wangzefeng** [comment]
Thanks @quinton-hoole, @raravena80 and @amye, will schedule the presentation once the proposal is ready.

**Comment by lizrice** [comment]
LGTM for annual review (I have not looked at the Incubation proposal)

**Comment by alena1108** [comment]
LGTM for Sandbox Annual Review

**Comment by justincormack** [comment]
LGTM for annual review.

**Pull request merged**
