### PR TITLE
OpenEBS Incubation Stage Proposal

### PR DESCRIPTION
**Pull request by kmova**
OpenEBS has been a CNCF Sandbox project since May 2019.
The project and community have grown considerably over the last year. We would like OpenEBS to be considered for incubation.

Signed-off-by: kmova <kiran.mova@mayadata.io>

### CODE REVIEW

**Comment by kmova** [comment]
Initial presentation was made to CNCF SIG Storage on Aug 26th. 
- Presentation Link: https://docs.google.com/presentation/d/14ZaiTFZV6551wrlNhGTWUWcaV26zAKc6G0zSXVwTC2s/edit?usp=sharing
- One of the AI from the meeting was to follow-up on the details of various OpenEBS code repositories and their dependencies.

**Comment by kmova** [comment]
A quick note  - We had follow-up conversations and OpenEBS maintainers are working on the feedback provided by the SIG-Storage team.

**Comment by lukaszgryglicki** [comment]
Just FYI - DevStats run on top of `OpenEBS` :D

**Comment by RichiH** [comment]
@kmova I am volunteering to review & shepherd on TOC side. I last touched OpenEBS quite some time ago and will need to delve in again.

Do you have time to set up a 30m call? Alternatively, is there a recurring public project meeting I can join?

**Comment by RichiH** [comment]
As per CNCF Slack `#toc`, in https://cloud-native.slack.com/archives/C0MP69YF4/p1656112677562789 I have unearthed some concerns about the health of the project since November 2021. I am trying to follow up and would appreciate any information others might have.

**Comment by RichiH** [comment]
As per https://github.com/openebs/openebs/pull/3525 , OpenEBS is trying to onboard new maintainers.

In https://github.com/openebs/openebs/issues/3548 I requested a general update on who is currently a maintainer.

**Comment by RichiH** [comment]
Hi everyone; I'll also comment in https://github.com/cncf/toc/issues/905 to make sure this reaches everyone. Could you please update this PR with the most up to date information?

CC @nconnolly1 @GlennBullingham @gila @kmova @pawanpraka1 @vishnuitta

**Comment by RichiH** [comment]
As per https://github.com/cncf/toc/issues/1051 , CNCF TOC has moved forward with an archival proposal for the OpenEBS project.

For the notice in the project issues, please see https://github.com/openebs/openebs/issues/3634

CNCF staff will reach out to all project maintainers and the CNCF end user community.

CC @nconnolly1 @GlennBullingham @gila @kmova @pawanpraka1 @vishnuitta

**Pull request closed without merging**
