### PR TITLE
[Proposal] CNCF Big Data & AI TAG

### PR DESCRIPTION
**Pull request by BinaryHB0916**

### CODE REVIEW

**Comment by amye** [comment]
@BinaryHB0916: do have proposed co-chairs for this TAG?

**Comment by raravena80** [comment]
I believe some discussions in the past have happened where it was determined that most of the projects/work in this space fall under the LF AI https://lfaidata.foundation/.  Also, TAG-Runtime has been targeting one specific area related to running ML workloads in cloud native environments (MLOps space)

**Comment by sighingnow** [comment]
> @BinaryHB0916: do have proposed co-chairs for this TAG?

We are still trying to reach out to potential co-chairs for this TAG.

> I believe some discussions in the past have happened where it was determined that most of the projects/work in this space fall under the LF AI https://lfaidata.foundation/. 

Hi @raravena80, I believe this Bigdata & AI TAG and LF AI have different scope. Most of the projects in LF AI are standalone projects that can perform bigdata & AI computations. Many projects in LF AI even may cannot be easily deployed in cloud-native environment (on Kubernetes) without efforts from third-party tools or the end-users.

This TAG for Bigdata & AI, however, in focused on better support from the cloud-native infrastructures for big-data & AI applications, by identifying the challenges, prompting the collaboration, improving the interoperability, and finally reaching a consensus of a new could-native paradigm. This TAG doesn't aim at making the bigdata & AI engine itself better, but aim at making those bigdata & AI engines works better on cloud-native infrastructures.

To archive this goal, there are a lot of opportunities and more attention as welll as more technical investment are required in this area, including but not limited to runtime, e.g., in the area of storage, networking, security, scalability, scheduling, operation and maintenance automation.

**Comment by amye** [comment]
@BinaryHB0916 - @sighingnow: is this still active?

**Comment by BinaryHB0916** [comment]
It gets postponed and please close this for now. Thanks.

**Pull request closed without merging**
