### PR TITLE
Akri 2022 Annual Review

### PR DESCRIPTION
**Pull request by kate-goldenring**
Annual review as recommended by the [CNCF TOC guidelines](https://github.com/cncf/toc/blob/main/process/sandbox-annual-review.md#how-to-file-your-annual-review).

Fixes https://github.com/project-akri/akri/issues/614

### CODE REVIEW

**Comment by kate-goldenring** [comment]
@amye are there any action steps we should take on our side for this?

**Comment by kate-goldenring** [comment]
@raravena80 are there any steps we should take here? What is the best way to have this reviewed?

**Comment by raravena80** [comment]
@kate-goldenring thanks for following up. We are starting a new annual review process (TAGs doing the reviews). We expect to start in the next 2 weeks. Stay tuned.

**Comment by raravena80** [comment]
Quick update. [Currently searching for a volunteer to do the independent review].(https://docs.google.com/spreadsheets/d/16LFpy6eDXu5SVnrs7klcZgupQN_8UM6LfV4a7J3kink/edit#gid=0).

**Review by cathyhongzhang — APPROVED** [review]
The project provides very useful functionality and fills a gap for k8s to support edge cloud. it is progressing well with a healthy community.

**Pull request merged**
