### PR TITLE
Harbor Graduation Proposal

### PR DESCRIPTION
**Pull request by michmike**
Harbor is currently a CNCF Incubating Project. Harbor will present in the [November 5th, 2019 CNCF TOC call](https://github.com/cncf/toc#meeting-time). As part of this review, we would like Harbor to be considered for Graduation.

The CNCF Technical Due Diligence for Graduating Harbor is located at https://docs.google.com/document/d/15gX7EeeXQThEvVMGpL-0a1mOwGuByLtMfvXNJaKT0A0/edit?usp=sharing. Let us know if anything else is needed.

The consolidated SIG review docs are at http://bit.ly/harbor-graduation-dd

Signed-off-by: Michael Michael <michmike@users.noreply.github.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
RFC @cncf/toc, any volunteers to handle due diligence? cc: @amye

**Comment by xiang90** [comment]
I can help on the DD if it is not very urgent.

**Comment by michmike** [comment]
@xiang90 we created the Tech-DD document and its pretty comprehensive in aiding for your review. I will send a link to it tomorrow morning. we are trying to button up approvals from a couple of customers to include them in the reference section.

**Comment by xiang90** [comment]
> Harbor will present in the November 5th, 2019 CNCF TOC call. As part of this review, we would like Harbor to be considered for Graduation.

@caniszczyk @monadic @lizrice For graduation project, should the project be reviewed by the SIG first?

**Comment by michmike** [comment]
@xiang90 , i added a link to the Tech-DD document that we prepared. https://docs.google.com/document/d/15gX7EeeXQThEvVMGpL-0a1mOwGuByLtMfvXNJaKT0A0/edit?usp=sharing

Please note that we are scheduled for a TOC review on Nov 5th. Is that sufficient time for you to review this document and do the due diligence? 

Harbor is apply for graduation based on the v1.2 of the Graduation Criteria. I am not sure if that matters on the SIG review...

thank you!

**Comment by caniszczyk** [comment]
@xiang90 which SIG is most appropriate, storage?

**Comment by quinton-hoole** [comment]
@xiang90 @caniszczyk Harbour falls within SIG-Runtime [charter](https://docs.google.com/document/d/1rftGB1Wkc_VcG9gz0072uCUHIddViGtLwaO4boEb4qA/edit?ts=5dc1a6fb).  Also, I think that sig-storage should review the storage-related aspects, and sig-security the security-related ones.  I can co-ordinate/lead this from SIG-Runtime.

**Comment by michmike** [comment]
> @xiang90 @caniszczyk Harbour falls within SIG-Runtime [charter](https://docs.google.com/document/d/1rftGB1Wkc_VcG9gz0072uCUHIddViGtLwaO4boEb4qA/edit?ts=5dc1a6fb). Also, I think that sig-storage should review the storage-related aspects, and sig-security the security-related ones. I can co-ordinate/lead this from SIG-Runtime.

@quinton-hoole how would you like to proceed in this review? We have the technical due diligence document that offers a great start to get to know Harbor. we are available to meet and discuss any concerns or even to kick things off. please let me know. thanks!

**Comment by quinton-hoole** [comment]
I've created http://bit.ly/harbor-graduation-dd to consolidate the SIG reviews.

**Comment by michmike** [comment]
@quinton-hoole  can we also please assign owners for this review and establish a timeframe as well?
I understand that you are a chair in both storage and runtime SIGs, so essentially you may be representing both SIGs.

@pragashj, @ultrasaurus, @dshaw, who can do this review and due diligence from sig-security?
@mattfarina  and @bryanl , who can do this review from the sig-app-delivery?

thanks!

**Comment by quinton-hoole** [comment]
@michmike Yes, I can follow up on this.  Everyone is pretty occupied with KubeCon coming up in a week, so this might take a while.

**Comment by xiang90** [comment]
@michmike @caniszczyk 

The DD looks solid. I made a few minor comments that should be addressed soon. One suggestion I have for Harbor is to create a maintainer diversity and encouragement plan, since most of the active maintainers are from VMWare.

For the SIG review, I suggest to have a single meeting/review for all SIGs reviewers. Or it will be too much a burden for both Harbor and the SIGs.

@quinton-hoole the current DD is here https://docs.google.com/document/d/15gX7EeeXQThEvVMGpL-0a1mOwGuByLtMfvXNJaKT0A0/edit?usp=sharing

**Comment by michmike** [comment]
thank you @xiang90. We appreciate the thorough review. I will make the updates to the doc as per your suggestion. 
In terms of the sig-review, the Harbor team is good to participate in one or more reviews with the relevant SIGs. Who will/can schedule them?

**Comment by michmike** [comment]
@quinton-hoole can we schedule some time to move this review along? thanks in advance!

**Comment by quinton-hoole** [comment]
Yes, will do. My apologies for the delay.

**Comment by michmike** [comment]
happy new year everyone. @quinton-hoole , can we set up some time to move along this process?

**Comment by raravena80** [comment]
Update: we reviewed the DD in SIG-Runtime and it looks very solid. @michmike has also addressed all the comments and concerns in the DD document. We recommend graduation: https://github.com/cncf/sig-runtime/issues/7

**Comment by saad-ali** [comment]
CNCF SIG Storage Due Diligence Report can be found [here](https://github.com/cncf/sig-storage/pull/52#issuecomment-593797451). tldr; Some concerns were raised, leaving it up to TOC to determine if they are blocking or not.

**Comment by xiang90** [comment]
@michmike 

According to the main SIG suggestions, we are still waiting for the review result from SIG Security/App.

See this SIG review doc here: https://docs.google.com/document/d/1IxakOhnAPjN3RFn1jYLvDCAaC_-mj3n-1StJ1CKGdkM/edit.

@quinton-hoole @amye 
Can you help to ask the required SIGs for a review. Thanks!

**Comment by xiang90** [comment]
> CNCF SIG Storage Due Diligence Report can be found here. tldr; Some concerns were raised, leaving it up to TOC to determine if they are blocking or not.

We discussed this within the TOC community. We do not feel the dependency on PGSQL or Redis is a blocker.

**Comment by michmike** [comment]
> @michmike
> 
> According to the main SIG suggestions, we are still waiting for the review result from SIG Security/App.
> 
> See this SIG review doc here: https://docs.google.com/document/d/1IxakOhnAPjN3RFn1jYLvDCAaC_-mj3n-1StJ1CKGdkM/edit.
> 
> @quinton-hoole @amye
> Can you help to ask the required SIGs for a review. Thanks!

hi @xiang90 , we are working with sig-security on the review right now under item https://github.com/cncf/sig-security/issues/369.

However, i really don't see a need to review with sig-apps as well. i think having 3 sig's review Harbor  was already taxing on the team, but it was the right thing to do. From this comment, we talked about having those 3 SIGs review harbor (security, storage, runtime). https://github.com/cncf/toc/pull/311#issuecomment-549921418. Do you see a specific need for sig-apps to also review Harbor?

**Comment by michmike** [comment]
> > CNCF SIG Storage Due Diligence Report can be found here. tldr; Some concerns were raised, leaving it up to TOC to determine if they are blocking or not.
> 
> We discussed this within the TOC community. We do not feel the dependency on PGSQL or Redis is a blocker.

this is great news. thank you!

**Comment by raravena80** [comment]
FYI.  I've requested [SIG-Security](https://github.com/cncf/sig-security/issues/369#issuecomment-604002766) to update the [unified doc](http://bit.ly/harbor-graduation-dd) once they have completed their review.

I've also requested [SIG-Storage](https://github.com/cncf/sig-storage/pull/52#issuecomment-604121869) to update the doc (with their completed review) and opened and [issue](https://github.com/cncf/sig-app-delivery/issues/24) with SIG-App-Delivery.

**Comment by michmike** [comment]
xref the sig-app-delivery report on Harbor Graduation
From the report 

> Note, the review conclusion is Harbor is ready for the CNCF Graduation stage without further concerns.

https://github.com/cncf/sig-app-delivery/pull/25

**Comment by xiang90** [comment]
@michmike 

Just checked the status of the sig review: https://docs.google.com/document/d/1IxakOhnAPjN3RFn1jYLvDCAaC_-mj3n-1StJ1CKGdkM/edit#heading=h.3thhannm57mq

It seems that the security sig is still reviewing the project?

**Comment by michmike** [comment]
@xiang90 , sig-security has completed the bulk of the review and the team is in the last stage of putting down the assessment notes. Should be done in a couple of days. What else would you like to see before asking for a vote?

**Comment by dshaw** [comment]
Harbor has completed the Security Assessment with SIG-Security. https://github.com/cncf/sig-security/issues/369

**Comment by xiang90** [comment]
> @xiang90 , sig-security has completed the bulk of the review and the team is in the last stage of putting down the assessment notes. Should be done in a couple of days. What else would you like to see before asking for a vote?

If SIG security suggests for graduation, we should update the due diligence doc to reflect that (probably also clean up the doc a little bit). then we should call for a vote.

**Comment by raravena80** [comment]
@dshaw could you or someone who made the SIG-Security assessment update the combined DD doc: http://bit.ly/harbor-graduation-dd? Thanks!

**Comment by dshaw** [comment]
SIG-Security has complete our due diligence and [recommends Harbor for graduation](https://docs.google.com/document/d/1IxakOhnAPjN3RFn1jYLvDCAaC_-mj3n-1StJ1CKGdkM/edit#heading=h.3thhannm57mq).

**Comment by michmike** [comment]
@dshaw thank you so much for the excellent work by sig-security. It was a very valuable exercise.

@xiang90 would the next step be to kick off the public voting period for Harbor?

**Comment by michmike** [comment]
@quinton-hoole , since you are the only one with edit writes on the doc, can you please approve all the comments in there by all the sigs?
http://bit.ly/harbor-graduation-dd

**Comment by michmike** [comment]
> @quinton-hoole , since you are the only one with edit writes on the doc, can you please approve all the comments in there by all the sigs?
> http://bit.ly/harbor-graduation-dd

thank you Quinton for cleaning up the doc. @xiang90, anything else you would like to see?

**Comment by xiang90** [comment]
@michmike Can you resolve the merge conflict?

@caniszczyk We are ready to call for a vote. The DD is ready. We discussed the dependency issue raised by SIG Storage. The majority of TOC believes that having external dependencies on popular non-CNCF open-source projects (like Redis or pgsql) are fine.

**Comment by amye** [comment]
Harbor is now in public comment period, the vote will be called on May 26th.

**Comment by VinodAnandan** [comment]
Could someone please let us know why this submission needs to be prioritised over others (especially NATS)? Why is this submission not challenged the same way as NATS ("_the requirement for a graduated project not to be under the sole control of one organisation has been an issue_")

https://harbor.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&from=now-5y&to=now&var-period=q&var-metric=activity&var-repogroup_name=All&var-companies=All

Cc @lizrice @michelleN @quinton-hoole @ColinSullivan1 @derekcollison @lucperkins

**Comment by caniszczyk** [comment]
The TOC can prioritize things to their liking and judgement, they have final authority here. An analogy here is the US Supreme Court, I may not like every ruling but they get to choose what cases they accept and their priority.

For maintainer diversity, I think it's important to look at a few things, the link you mentioned above is a good one along with the official maintainer list and how receptive the project has been in adding new maintainers over time: http://maintainers.cncf.io and also a projects direct maintainers governance: https://github.com/goharbor/community/blob/master/MAINTAINERS.md

Also if you look at our project health dashboards, you can see things a bit more clearly if a project is behaving in a healthy manner:
https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=NATS
https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Harbor

**Comment by VinodAnandan** [comment]
@caniszczyk  Thanks for your reply, I believe the particular concern @lizrice  raised was about the "sole control of one organisation" not about health. Even in the health link's data, it indicated how solely one particular company controls this project. What is the acceptable sole control for a graduated project? Or is it just about names in a particular document? In another submission, I've noticed that the maintainers in the document were not "Technically" maintainers ( https://github.com/cncf/toc/pull/379#issuecomment-609589846 )

**Comment by mhurtrel** [comment]
Just wanted to quickly share some insights about the great job done by the Harbor team in the last year if that can contribute to TOC appreciation.

I am PM for a large Europe-based cloud provider. When we experimented with Harbor a year ago as a possible solution for our registry product, starting with great feedback from customers and prospects using Harbor onprem and in enterprise deployments (custom or as part of some entrerprise suite). The project was clearly mature on the functional basis, but it still had room for improvement in two areas: documentation and control by one company. Both of those concerns have been resolved by the project since.

We quickly entered the community (and the great bi-weekly community meeting and reactivity on the Slack channels and in 1-1 basis made it easy) and were quickly reassured by the fact that the team had its sights on a common vision with us and were in fact addressing some of our concerns.

After months of working with the team, issues, PRs, and discussions, we contributed to the community what is now integrated asthe official Harbor operator (currently in v0.5 as a subfolder in the project repo).

Our company now has a stake in the Harbor project, adding even more diversity than what was already happening in the last year, and we saw a big improvement around the documentation effort in the last 6 months.

I think Harbor is very stable and massively used in the field, and even though the registry is being often considered a commodity, Harbor has its place as a key component in our solution and we are very happy with the community and resulting product.

**Comment by monadic** [comment]
That's really great to hear.  Thanks for the testimonial @mhurtel

**Comment by JustinCappos** [comment]
I'd also like to say that the Harbor team has made a really substantial
effort toward securing their system.  The overall stitching of large
components gives them a very challenging environment to secure.  However,
both the SIG-Security Assessment and the security audits they had from
various firms were positive about the design, effort, and security posture
of the project.

**Comment by VinodAnandan** [comment]
@mhurtrel Thank you for your contribution to the project. The harbor project has made an important change by replacing the Clair with Aqua’s Trivy as the default image scanner. I believe Clair was the default scanner for 3+ years. Has this change been communicated to the harbor users via the community channels and requested feedback? Also, does the harbor team know if the Trivy project has any plans to join the CNCF similar to Clair?

**Comment by michmike** [comment]
Yes the change from Clair to Trivy was brought up over 10 times in community meetings, planning meetings for the 2.0 release and in blog posts. None of our users or contributors raised any concerns. In contrary, the change was celebrated. I can't speak to Trivy's goals around CNCF. You can ask Liz Rice in private.

**Comment by michmike** [comment]
Be aware that Clair was not deprecated. It is still a built in component that's deployed with Harbor. It is just that now Trivy is the default scanner.

**Comment by VinodAnandan** [comment]
@michmike Thank you for your reply. Has this ever been notified in the Harbor mailing lists asking for feedback? I don't remember seeing one, such notifications would be really helpful.

Also, I think if the website will explicitly mention details of all projects that are vertically integrated to offer the core features ( Security and vulnerability analysis: Clair, Trivy, etc., Content signing and validation: Notary, etc.) in Harbor will help to reduce user confusion.

**Comment by caniszczyk** [comment]
Hey @michmike can you fix the the conflicts in the branch?

Harbor has enough votes to graduate:

+1 Binding: *note: Quorum is 10 as Jeff Brewer has been away*
7 TOC votes:
Sheng Liang: https://lists.cncf.io/g/cncf-toc/message/4773
Xiang Li: https://lists.cncf.io/g/cncf-toc/message/4775
Katie Gamanji: https://lists.cncf.io/g/cncf-toc/message/4784
Justin Cormack: https://lists.cncf.io/g/cncf-toc/message/4800
Liz Rice: https://lists.cncf.io/g/cncf-toc/message/4816
Alena Prokharchyk: https://lists.cncf.io/g/cncf-toc/message/4818
Michelle Noorali: https://lists.cncf.io/g/cncf-toc/message/4836
Saad Ali: https://lists.cncf.io/g/cncf-toc/message/4840

**Comment by michmike** [comment]
working on this... :)

**Comment by michmike** [comment]
@caniszczyk  you can merge it now

**Comment by caniszczyk** [comment]
Thanks @michmike and welcome!

**Pull request merged**
