### PR TITLE
ChaosBlade incubation proposal

### PR DESCRIPTION
**Pull request by MandssS**
This PR contains a proposal for ChaosBlade to be accepted into the CNCF Incubation stage.

ChaosBlade is a versatile Chaos Engineering platform that orchestrates chaos experiments on Kubernetes and Host environments. 

By covering comprehensive fault injection methods in container, Pod, Node, network, file system, middleware, cloud vendor infrastructure, running application process, and even the kernel, ChaosBlade aims at providing a neutral, universal Chaos Engineering platform that enables cloud-native applications to be as resilient as they should be.

### CODE REVIEW

**Comment by caofujiang** [comment]
ChaosBlade是国内混沌工程领域的很优秀的工具，一个深度使用者的强烈推荐

**Comment by sshnull** [comment]
chaosblade支持多个场景的故障注入，便于开发、维护和扩展 ，chaosblade老炮推荐

**Comment by KeKe-Li** [comment]
chaosblade 开源越来越棒！

**Comment by binbin0325** [comment]
ChaosBlade has developed very well in the field of cloud-native chaos engineering with rich functions. It looks forward to entering cncf incubation

**Comment by aspnetdb** [comment]
ChaosBlade is an open-source chaos engineering platform. It provides a comprehensive set of tools and frameworks to help developers and operations teams inject faults, monitor, analyze, and recover in distributed systems, ultimately enhancing system resilience and stability.

**Comment by houlong2015** [comment]
chaosblade can perfectly applyed to kubernet or physical injection，and with the chaosblade-box，we can easily do any experiments , very good!

**Comment by peterZhang000** [comment]
The ChaosBlade tool contains chaos experiments in many fields. Chaos experiments in different fields are implemented by different projects.  gogoooooooo🚀

**Comment by ralf0131** [comment]
Hi @angellk, 
I think the chaosblade project belongs to the `tag-observability`. Maybe the label should be `tag-observability`?

The project has presented the latest update with `tag-observablity` including @alolita  on July 10. See the [meeting notes]( https://docs.google.com/document/d/1_QoF-njScSuGFI3Ge5zu-G8SbL6scQ8AzT1hq57bRoQ/edit) for more information.

**Comment by alolita** [comment]
Hi Karena,

Confirming Huxing and the ChaosBlade team presented at the APAC TAG
Observability meeting today with a overview of the project, its technical
features, adoption and contributor ecosystem.
Let me know if you have any questions.
Best,
Alolita

**Comment by spencercjh** [comment]
Chaosblade is one of China's earliest open-source projects in chaos engineering. Compared to similar projects like ChaosMesh or ChaosMeta, it has the largest user base and enterprise users in China.  While its success is undeniable, the Chaosblade community seems to lack activities. There are several problems in the community now.

- Ignore important GitHub issues and PRs like https://github.com/chaosblade-io/chaosblade/issues/986, https://github.com/chaosblade-io/chaosblade-exec-os/pull/163. Associated data is here: 
> https://chaosblade.devstats.cncf.io/d/12/issues-opened-closed-by-repository-group?orgId=1&var-period=d&var-repogroup_name=All
https://chaosblade.devstats.cncf.io/d/11/issues-age-by-repository-group?orgId=1&var-period=d&var-repogroup_name=All&var-prio_name=All&from=now-1y&to=now
https://chaosblade.devstats.cncf.io/d/10/pr-time-to-engagement?orgId=1&from=now-1y&to=now&var-period=d7&var-repogroup_name=All
https://chaosblade.devstats.cncf.io/d/19/open-pr-age-by-repository-group?orgId=1&from=now-1y&to=now

- Black box discussion of issues, no public explanation of major changes: https://github.com/chaosblade-io/chaosblade/pull/987 which leads to many question isseus like https://github.com/chaosblade-io/chaosblade/issues/1007 and there are still no response from maintainers now.
- Lack of maintenance staff to maintain the program. chaosblade is a mature and stable project, but that doesn't mean it doesn't need to be maintained.
- It seems that chaosblade is a closed org with no intention of developing new committers or maintainers from outside.

I know that the above problems is not only a problem of chaosblade, but also a common problem of most Chinese open-source projects, but I hope CNCF can do something about it. Let's build a better chaosblade and CNCF together!

**Comment by MandssS** [comment]
> Chaosblade is one of China's earliest open-source projects in chaos engineering. Compared to similar projects like ChaosMesh or ChaosMeta, it has the largest user base and enterprise users in China. While its success is undeniable, the Chaosblade community seems to lack activities. There are several problems in the community now.
> 
> * Ignore important GitHub issues and PRs like [网络放火，包留白名单端口失效导致机器失联 chaosblade-io/chaosblade#986](https://github.com/chaosblade-io/chaosblade/issues/986), [fix mem load cache mode bug chaosblade-io/chaosblade-exec-os#163](https://github.com/chaosblade-io/chaosblade-exec-os/pull/163), [chaoblade-tool does not support cgroupv2, when the container is  containerd，”cgroups load failed, cgroups: cgroup deleted“ chaosblade-io/chaosblade#1043](https://github.com/chaosblade-io/chaosblade/issues/1043).
> 
> Associated data is here:
> 
> > https://chaosblade.devstats.cncf.io/d/12/issues-opened-closed-by-repository-group?orgId=1&var-period=d&var-repogroup_name=All
> > https://chaosblade.devstats.cncf.io/d/11/issues-age-by-repository-group?orgId=1&var-period=d&var-repogroup_name=All&var-prio_name=All&from=now-1y&to=now
> > https://chaosblade.devstats.cncf.io/d/10/pr-time-to-engagement?orgId=1&from=now-1y&to=now&var-period=d7&var-repogroup_name=All
> > https://chaosblade.devstats.cncf.io/d/19/open-pr-age-by-repository-group?orgId=1&from=now-1y&to=now
> 
> * Black box discussion of issues, no public explanation of major changes: [fix: Temporarily disable server mode. chaosblade-io/chaosblade#987](https://github.com/chaosblade-io/chaosblade/pull/987) which leads to many question isseus like [1.7.3版本里面blade server的命令是删除了吗 chaosblade-io/chaosblade#1007](https://github.com/chaosblade-io/chaosblade/issues/1007) and there are still no response from maintainers now. Most of the valid and up-to-date information is in DingTalk groups but is not updated to the associated GitHub Issues or project docs.
>   image
> * Lack of maintenance staff to maintain the program. chaosblade is a mature and stable project, but that doesn't mean it doesn't need to be maintained. Especially chaosblade-operator, whose maintenance has almost come to a standstill.
> * It seems that chaosblade is a closed org with no intention of developing new committers or maintainers from outside.
> 
> I know that the above problems are not only problems of chaosblade, but also common problems of most Chinese open-source projects, but I hope CNCF can do something about it. Let's build a better chaosblade and CNCF together!

Thank you for your suggestion and advice on chaosblade. From your reply, I can feel your deep feelings for chaosblade, which makes me very touched. Regarding your question, I will reply here:
● The issue mentioned was not handled in a timely manner. Due to the recent busy development of new features and insufficient energy allocation, the issue reply was indeed not timely enough. But for important pr, they are basically merged in the new version.
● The server mode is deleted here for security reasons. An issue will be released later to explain the specific reasons.
● chaosblade is maintained by maintainers and community, and chaosblade-operator has also been released recently.
● Chaosblade has a complete contributor ladder, and recently a new maintainer has been successfully promoted. You are also very welcome to submit promotion proposals.
- https://github.com/chaosblade-io/community/blob/main/Contributor_Ladder.md

We will invest more time in issue management in the future. You are also very welcome to provide valuable comments in subsequent regular meetings. Of course, you are also welcome to join the maintenance work of chaosblade.  Let's build a better chaosblade and CNCF together!

**Comment by angellk** [comment]
Moved [application with new template](https://github.com/cncf/toc/issues/1387) to same place in the queue as this one. Closing to de-dupe. Thank you @MandssS !

**Pull request closed without merging**
