### PR TITLE
Karmada 2022 Annual Review

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
This PR adds Karmada 2022 annual review.

Signed-off-by: Kevin Wang <kevinwzf0126@gmail.com>

### CODE REVIEW

**Review by rajaskakodkar — COMMENTED** [review]
Karmada demonstrates continued and ongoing progress towards incubation as seen through: ongoing community growth and development, improvements to governance, presence of long term planning, versioned releases, increased adoption, and overall self-awareness.  Karmada is ready for incubation and has already applied for it https://github.com/cncf/toc/pull/986.
The TAG recommends the TOC continue sponsorship. The TAG also recommends the TAG/TOC/CNCF assist Karmada with the following: 

 Karmada should update the project maintainers listed in this [PR](https://github.com/cncf/toc/pull/954) with the ones who actively contribute to the project and reconcile with https://github.com/karmada-io/karmada/blob/master/MAINTAINERS.md.
Six out of the seven maintainers listed in the annual review, seem to be inactive in the Karmada project.
  - Last [commit](https://github.com/karmada-io/karmada/commit/711ea43fd93d51fa24eca9e074caebedae71367d) from [lfbear](https://github.com/lfbear) was in March 2022
 - There have been no public commits from https://github.com/zoroyouxi and https://github.com/carmark 
 - Last [commit](https://github.com/karmada-io/karmada/commit/9711b9e5f8bb7b42cb9b16014595295c6e112092) from [GitHubxsy](https://github.com/GitHubxsy) was in February 2021 
 - Last [commit](https://github.com/karmada-io/karmada/commit/de519b4370e7f0cf8d28278194f713e2add8a724) from [kevin-wangzefeng](https://github.com/kevin-wangzefeng) was in August 2022 
 - Last [commit](https://github.com/karmada-io/karmada/commit/08833eb18623d9862f049cd40287c333b6607bf2) from [mrlihanbo](https://github.com/mrlihanbo)  was in May 2022

**Comment by nikhita** [comment]
@kevin-wangzefeng can you update this PR based on @rajaskakodkar's recommendation?

Let's get this merged after those concerns are addressed.

**Comment by kevin-wangzefeng** [comment]
Thanks, @rajaskakodkar and @nikhita, my thoughts on this are:

1. An Annual Review is a snapshot of a project’s status during a certain period. The term for this report is from September 2021 to September 2022, the data is indeed outdated from the current perspective. Also Please note that this PR has been awaiting review for almost one year.
2. The maintainers are currently the top decision-making body in the Karmada community, covering both code and non-code activities. Counting maintainers’ contributions based solely on commits is not comprehensive.
3. We do face challenges in recording people’s non-code contributions. Any help with this would be greatly appreciated.
4. Karmada is currently under a [governance review](https://github.com/cncf/tag-contributor-strategy/issues/461) by tag-contributor-strategy. Once it’s done, we will update the project governance accordingly, including: 1) splitting roles relevant to code and non-code activities, 2) retiring inactive members.

**Review by nikhita — APPROVED** [review]
@kevin-wangzefeng sounds good.

> We do face challenges in recording people’s non-code contributions. Any help with this would be greatly appreciated.

Can you please work with TAG Contributor Strategy for this? cc @jberkus 

@cathyhongzhang as the other TOC Liaison, can you please approve this PR? We need at least two LGTMs from TOC members to merge.

**Review by cathyhongzhang — APPROVED** [review]

**Comment by cathyhongzhang** [comment]
LGTM

**Comment by nikhita** [comment]
From the Conducting Annual Reviews [doc](https://docs.google.com/document/d/1cE9zutKh3ZGzEzZr5CZ_ck66JJ1J5mLeNYELVLbxf-Q/edit):

> TOC members will then approve the Annual Review PR, 2 or more TOC members are required in order for Annual Reviews to be merged, after which it may be merged by CNCF Staff or any TOC member.

Merging.

**Pull request merged**
