### PR TITLE
proposal: Kube-OVN to Incubation

### PR DESCRIPTION
**Pull request by oilbeater**
Kube-OVN has join CNCF for about a year and a half. We have made great process and hope to go to next stage for incubation.

Please review the proposal and we are happy to here any advice. 

@oilbeater will be the main contact. Thanks!

### CODE REVIEW

**Comment by RichiH** [comment]
I'll sponsor & review this from the CNCF TOC side.

@oilbeater could you please update the PR, or confirm what all information is still current?

**Comment by oilbeater** [comment]
@RichiH Great to hear that, I have updated the PR, mainly some number updates.

**Comment by RichiH** [comment]
I went through the proposal & the underlying data and have a few initial questions:

## Adoption
  * Would some of your larger users be comfortable to share usage stats & use cases privately?
  * The uses cases on https://github.com/kubeovn/kube-ovn/blob/master/USERS.md seem largely copy and pasted, with Ubuntu's not a use case at all. Would it be possible to get more detailed information here?

## Contributors

According to https://kubeovn.devstats.cncf.io/d/5/companies-table?orgId=1 , contributions by Alauda Inc are consistently two orders of magnitude higher than for the second-highest contributor.

For the project lifetime, the top five look as such:

Rank | Company | Count
-- | -- | --
1 | AlaudaInc | 13668
2 | Inspur Group | 255
3 | China Telecom | 228
4 | 99Cloud Inc. | 114
5 | Intel Corporation | 51

Last two years (not quite 10k, but near enough for orders of magnitude):
Rank | Company | Count
-- | -- | --
1 | AlaudaInc | 9742
2 | Inspur Group | 207
3 | China Telecom | 127
4 | 99Cloud Inc. | 114
5 | EasyStack Inc. | 45

Last year:
Rank | Company | Count
-- | -- | --
1 | AlaudaInc | 6062
2 | Inspur Group | 86
3 | 99Cloud Inc. | 57
4 | China Telecom | 23
5 | Awanio | 15

The ratio of outside contributions went down, not up, in recent years. Is this ratio likely to increase? If yes, what specific steps and actions are being taken in this direction?

**Comment by oilbeater** [comment]
@RichiH 

# Adoption

> Would some of your larger users be comfortable to share usage stats & use cases privately?

I have talked with some of the largest community users, one of them are willing to share his story and I am waiting for others response. 

> The uses cases on https://github.com/kubeovn/kube-ovn/blob/master/USERS.md seem largely copy and pasted, with Ubuntu's not a use case at all. Would it be possible to get more detailed information here?

I have talked with guys in China Telecom CTYun and China Yealink before. Their use case are much similar, they are both building their own cloud by Kubernetes as the base and then use KubeVirt to provide VMs and Kube-OVN to provide a public cloud like network, for example VPC, Subnet and NatGateway.

For the Ubuntu case,  the Canonical Kubernetes chooses Kube-OVN as a network option that  can be found at https://ubuntu.com/kubernetes/docs/cni-kube-ovn

# Contributors

Some data is missing the the dashboard when group by company, lots of contributors that not fill their company information are not shown in the table. If compared with all contribution outside Alauda, it looks like this:

| Period | All Contribution | Alauda Contribution| Outside Contribution Ratio|
| ------ | ------ | ----- | ----- |
| All | 17260 | 13668 | 21% |
| Last Two Years | 12792 | 9742 | 24% |
| Last Year | 8547 | 6062 | 29% |
 
From this view the outside contribution ratio is increasing.

**Comment by RichiH** [comment]
Thanks for this! Please keep me informed as more users reply.

You are right, from that perspective the contributions look a lot better already.

**Comment by oilbeater** [comment]
@RichiH you can reach fanriming123@163.com who is working at China Telecom CTYun and building public edge cloud and jmdxjsjgcxy@gmail.com who previously worked at Yealink and build on prem cloud infrastructure and now is working at China Mobile also building public edge cloud. 

Both of them are not native in English if you need to talk with them in video any TOC that are familiar with Chinese might be helpful.

**Comment by RichiH** [comment]
Hi @oilbeater, I also reached out via Slack. Could we find 15m or 30m to talk about the current status and move from there?
15m: https://calendly.com/d/4y2-btw-vgg/15min
30m: https://calendly.com/d/3jr-sxj-hpz/30min

**Comment by RichiH** [comment]
Mengxin (@oilbeater), Kai, and myself had a call this morning and cleared up the way forward.

Several of the large users seem to be Chinese-only speakers, so @oilbeater will help with translation of their usage reports and also update information in this PR and in the linked resource, e.g. usage.md.

**Comment by oilbeater** [comment]
Hi @RichiH , I have update the PR stats and the adopter interview is translated here https://docs.google.com/document/d/1bYJIOsd9xvn2TDPKxDRWOAc450hG-1RiGouEw4EWoS8/edit?usp=sharing

**Comment by TheFoxAtWork** [comment]
👋🏻  Thank you Richi for sponsoring this project and getting is started!  has the DD doc been created yet or does this still need to happen? I want to ensure when this is transitioned to a new TOC member they have all the links, content, and status so they can continue to make progress here. I know @linsun expressed interested in sponsoring this once the [KCCN freeze](https://github.com/cncf/toc/blob/4caa30a7f1b7d621eee174e020f20c1f8fe3f395/process/project_proposals.md#kubeconcloudnativecon-freeze) is lifted and we've completed onboarding for the new TOC (by February 22nd).

**Comment by linsun** [comment]
I'm self assign this from @RichiH - will review soon

**Comment by TheFoxAtWork** [comment]
@linsun let me know if you need assistance on this one once we know where it was at/left off.  Would recommend checking in with @oilbeater to understand where this was at prior to Richi's transition to TOC Emeritus.

**Comment by linsun** [comment]
Thanks @TheFoxAtWork! I've reached out to @oilbeater on slack.

**Comment by linsun** [comment]
@oilbeater informed me via slack that he has updated the PR to latest info.

**Comment by linsun** [comment]
Hi @oilbeater Have you started the DD checklist for the project?  I don't see any referred to this github issue, so I started a [doc](https://docs.google.com/document/d/1J2uCpZWkDta9f2nnA-v73npW99cS0GMGc29LGgPyqMQ/edit?usp=sharing) based on the new [template](https://github.com/cncf/toc/blob/main/operations/toc-templates/template-dd-pr-incubation.md).  I have a bunch of questions for you in the [doc](https://docs.google.com/document/d/1J2uCpZWkDta9f2nnA-v73npW99cS0GMGc29LGgPyqMQ/edit?usp=sharing), can you please take a look and provide answers in the doc directly as comments? Many thanks!

**Comment by oilbeater** [comment]
Hi @linsun I haven't started any DD checklist before and I will update the answers in next week soon. 

RichiH and I had a meeting before to discuss how to update the documentation and review with the adopters. I am not sure if this is the official kickoff meeting.

**Comment by oilbeater** [comment]
Hi @linsun, I have replied the document question, please let me know if you still have any question

**Comment by linsun** [comment]
Hi @oilbeater, thanks!  That sounds like the kickoff meeeting. I'll review what you replied in the document and get back later this week to see if we need another meeting. In the meanwhile, I'd recommend you schedule the TAG presentation and a few other items identified in the doc comment.

**Comment by linsun** [comment]
Hi @oilbeater, I have reviewed the update you provided and identified the following gaps before I can submit the DD checklist for incubation:

- [ ] TAG network presentation
- [ ] Obtain feedback & recommendation from TAG network chairs
- [ ] Address vendor neutral content concerns I highlighted in the doc in yellow
- [ ] TAG contributor strategy review
- [ ] Restart public meetings and integrate them with CNCF calendar
- [ ] Update roadmap doc. Clear doc on how to suggest changes to roadmap.
- [ ] Document release process
- [ ] Security review.

Please keep me posted on the progress and let me know if you have any questions. Thank you!

**Comment by oilbeater** [comment]
@linsun Thanks, I will update ASAP

**Comment by linsun** [comment]
Hi @oilbeater - just wanted to follow up to see if there is any update. I'll also reach out on slack to see if we can get a meeting scheduled.

**Comment by linsun** [comment]
Hi @oilbeater per our offline conversation - I am excited to see the progress you made:

1) Created an issue for TAG contributor review
2) Preparing for TAG network presentation
3) Preparing the self-assessment  for security review

Based on our current assessment, the project isn't ready for incubation in the next 3-6 months given the community meeting needs to be restarted. During a recent TOC review for the project, we would like to free up TOC resource to work on another project while getting yours ready, that is why we lean towards to close this issue and ask you to resubmit when you meet the requirements given it would probably take you 6 months to meet the requirement. You can continue to work on fulfilling the requirements in the meanwhile per our discussion.

When you resubmit, the TOC can give your project high priority given it is a resubmit for the project.

cc @TheFoxAtWork @nikhita if this is reasonable, we can close the issue.

**Comment by TheFoxAtWork** [comment]
Concur - i want to ensure we dont lose the existing work that has already been done by the team. @linsun do you have a recommendation for how we may integrate this into our new workflow for projects moving levels? particularly if the project is returning?  We could add a new "state" to our board or label.  @jeefy do you have ideas here? I dont want us to lose track.

**Comment by linsun** [comment]
Hi @TheFoxAtWork adding a new state to the board could be useful for us to easily track which ones are planning to return or already returned so we could recommend TOC members to pick up available ones from this state first when they become available.

**Comment by TheFoxAtWork** [comment]
I'll go ahead and add the column.  I'll also update the DD-guide to reflect this new state.

**Comment by linsun** [comment]
Thanks @TheFoxAtWork! Should I close this and un-assign myself, and start look for next project?

**Comment by linsun** [comment]
Mark as not-ready label. For reference, @oilbeater, this is the new process for project to reapply and gain high priority when becoming ready, captured by @TheFoxAtWork in her PR: https://github.com/cncf/toc/pull/1344

Going to close - please reopen/reapply when the project meets the requirements outlined earlier in this issue. Do reach out if you have any questions!

**Pull request closed without merging**
