### PR TITLE
infrakit proposal

### PR DESCRIPTION
**Pull request by chungers**
Per project submission process, please review this PR in consideration for accepting [InfraKit](https://github.com/docker/infrakit) into CNCF.

Here are the [slides](https://docs.google.com/presentation/d/1Lzy94UNzdSXkqZCvrwjkcChKpU8u2waDqGx_Sjy5eJ8/edit?usp=sharing) from the CNCF TOC meeting on June 6, 2017, where InfraKit was presented.   There have been follow-up questions on comparison of InfraKit to other systems.  They have been documented in the proposal, as well as, in [this email thread](https://lists.cncf.io/pipermail/cncf-toc/2017-June/000982.html).

Additional information on InfraKit:
  + [Original blog announcement](https://blog.docker.com/2016/10/introducing-infrakit-an-open-source-toolkit-for-declarative-infrastructure/)
  + [Docker Swarm use case](https://blog.docker.com/2017/03/infrakit-docker-swarm-mode-fault-tolerant-self-healing-cluster/)

Thank you.

Signed-off-by: David Chung <david.chung@docker.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
Thanks for the proposal @chungers, according to the CNCF process, the @cncf/toc needs to formally invite InfraKit for a proposal. This decision will most likely be made at the next TOC call, there's a bit of a backlog of projects that the TOC needs to take an action on.

Thanks for your patience :)

**Comment by chanezon** [comment]
Sorry @caniszczyk it wasn't clear to us, I thought we were supposed to send the PR after the presentation, to provide formal material for a vote. You might want to update https://github.com/cncf/toc/blob/master/process/project_proposals.adoc because that invitation step is not clear.
Should we wait for a formal invitation for Notary and TUF as well?

**Comment by caniszczyk** [comment]
@chanezon no worries, our fault for not making this more clear, however, I completely advise projects to start on a proposal before being formally invited for a vote as a way get feedback from the wider community

**Comment by chanezon** [comment]
Thank you @caniszczyk. Should we send the Notary/TUF proposal as a PR as well?

**Comment by caniszczyk** [comment]
no interest from @cncf/toc at the moment, if you would like to present in the future please open another issue

**Pull request closed without merging**
