### PR TITLE
Antrea 2023 Annual Review

### PR DESCRIPTION
**Pull request by antoninbas**
For https://github.com/antrea-io/antrea/issues/5469

### CODE REVIEW

**Comment by kgamanji** [comment]
Thank you for completing the sandbox annual review for the project. Overall the project goals and community have been consistent throughout the last year. Since the project is considering applying for incubation, here are a few recommendations:
-  Work on bringing in and mentoring new maintainers, if possible from different organizations. Welcoming and retaining new maintainers is essential for the long-term success of the project
- Focus on expanding the adopter's list. While 3 organizations are listed in the Adopters.md file, no new users were added in the last year. During Incubation DD the TOC will evaluate the scope and scale of the usage, hence, would recommend increasing your end user base 
- Update the roadmap to include milestones, goals, and releases where appropriate. Currently, most of the items on the roadmap were added 2-4y ago
- Review the Incubation level criteria and perhaps explore the current status of several incubation projects, their maturity and processes, and community activity

**Comment by antoninbas** [comment]
Thanks for the feedback @kgamanji, we will take this into account

**Comment by antoninbas** [comment]
@kgamanji I have opened an issue for updating our ROADMAP document, and we will discuss / take action in then next couple of weeks. Is this a blocker to merge this PR (annual review)?

**Comment by amye** [comment]
Marking this as complete, annual reviews are no longer a requirement for sandbox. 
We'll be rolling out more efficient ways to show project health and metrics in 2024.

**Comment by antoninbas** [comment]
For what it's worth, we have updated our ROADMAP :)

**Pull request merged**
