### PR TITLE
Project Proposal: NATS

### PR DESCRIPTION
**Pull request by ColinSullivan1**
As requested during the January 16, 2018 CNCF TOC meeting ([minutes](https://docs.google.com/presentation/d/1fJ2luQv9JkwFfpg6i775gP6JH1zB21yiZSjJBiIG8ZI/edit#slide=id.g2ee26d7733_0_49)), we  submit [NATS](https://nats.io) for consideration to be included as a CNCF project.

The Google document where this was drafted can be found [here](https://docs.google.com/document/d/1s9wPNq_BvObnqxySR_ByaPCbs-Y1GB5tI7zoBvAF3nQ/edit).

### CODE REVIEW

**Comment by caniszczyk** [comment]
Thanks @ColinSullivan1!

**Comment by josephjacks** [comment]
I'm excited about the NATS project. Messaging and integration middleware paradigms have changed radically in the cloud-native era and NATS represents a view into the future of application-to-application and service-to-service IPC.  NATS is a great fit for the CNCF.

**Comment by justincormack** [comment]
I think you mean 2018 not 2017! This is for an Inception project still?

**Comment by ColinSullivan1** [comment]
@justincormack Thanks!  I updated the PR description.  It is, although if the committee feels we can move ahead to Incubating we'd be happy to accommodate.

**Comment by caniszczyk** [comment]
I'd prefer to leave at inception for now cc: @cncf/toc

**Comment by justincormack** [comment]
I can't find any reference to who the committers are or the governance process. There is a good contribution guide https://nats.io/documentation/contributing/ but looking at the repos I can't see who the committers are anywhere.

**Comment by caniszczyk** [comment]
@justincormack it's not a requirement that projects have governance fully figured out before they propose the project, it's something that CNCF can help with as the project enters inception/incubation (although it's nice if projects have governance defined in advance)

**Comment by justincormack** [comment]
@caniszczyk sure, but I do want to know who the committers are...

**Comment by caniszczyk** [comment]
@justincormack as part of that process, they should definitely have the equivalent of a MAINTAINERS.md :)

**Comment by ColinSullivan1** [comment]
@justincormack , governance advice was one of our asks, so any advice there would be much appreciated.  We can add MAINTAINERS.md to our repositories.

**Comment by vongosling** [comment]
HI,guys, how do nats deal with LF another project, openmessaging,http://openmessaging.cloud/.

**Comment by dankohn** [comment]
@vongosling I'm glad you joined in. My impression was that OpenMessaging was actually a closer fit to some work taking place in the CNCF's Serverless working group on OpenEvents: https://github.com/cncf/wg-serverless#openevents

To answer your specific question, though, the presence of OpenMessaging in the LF has no effect on the decision for whether NATS comes into CNCF. CNCF already has multiple competing projects in some areas (e.g., containerd and rkt, linkerd and envoy).

**Comment by vongosling** [comment]
@dankohnI Thanks for your reply, yeah, I have learned more about CNCF competing projects, also, I have followed up the  CNCF Serverless working group long times. Actually, OpenMessaging stream parts have a similar closer roadmap to it. But, It is just parts of OpenMessaging . Nowadays, more and more company, not only from China, they all want to be involved in OpenMessaging standard, and I am very glad to introduce the further development under TSC's endeavor at the end of a month :-)

**Comment by derekcollison** [comment]
I will look into openmessaging, was not aware of it prior. Thanks @vongosling

**Comment by vongosling** [comment]
My pleasure @derekcollison , if you have any suggestion about OpenMessaging, please let us know :-)

**Comment by vbatts** [comment]
seems like there were lots of comment conversation on the draft that does not translate well to github PR.

**Comment by caniszczyk** [comment]
the @cncf/toc vote is out for NATS to come in as incubation level: https://lists.cncf.io/g/cncf-toc/message/1843

**Comment by caniszczyk** [comment]
Hey everyone, I'm happy to announce that NATS has been accepted into CNCF as an INCUBATION level project (sponsored by Alexis Richardson).

+1 TOC binding votes (8 / 9):

- Sam Lambert: https://lists.cncf.io/g/cncf-toc/message/1845
- Alexis Richardson: https://lists.cncf.io/g/cncf-toc/message/1847
- Camille Fournier: https://lists.cncf.io/g/cncf-toc/message/1874
- Solomon Hykes: https://lists.cncf.io/g/cncf-toc/message/1882
- Jonathan Boulle: https://lists.cncf.io/g/cncf-toc/message/1883
- Ken Owens: https://lists.cncf.io/g/cncf-toc/message/1889
- Ben Hindman: https://lists.cncf.io/g/cncf-toc/message/1890
- Brian Grant: https://lists.cncf.io/g/cncf-toc/message/1891

We'll be working with the NATS community over the next few weeks to welcome them to the CNCF project family. Thanks again to everyone who voted and participated in the due diligence process: https://github.com/cncf/toc/blob/master/process/due-diligence-guidelines.md

Finally, please welcome the NATS community!

**Pull request merged**
