### PR TITLE
BFE proposal as a CNCF SandBox project

### PR DESCRIPTION
**Pull request by iyangsj**
This PR is related to the BFE proposal as a CNCF SandBox project as described in issue #452.

### CODE REVIEW

**Comment by caniszczyk** [comment]
@iyangsj the next step is scheduling a review by SIG Network, @amye can help there

**Comment by tizhou86** [comment]
Hi @amye , we'd like to schedule a project review at next sig-network routine meeting on June 18th if available, thanks!

**Comment by amye** [comment]
You're on the presentation schedule for June 18th, see meeting[ agenda](https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q/edit#heading=h.vmi3gay3yroa)

**Comment by leecalcote** [comment]
Looking forward to today's presentation!

**Comment by caniszczyk** [comment]
BFE was accepted into the sandbox: 
https://lists.cncf.io/g/cncf-toc/message/4853

project onboarding will happen here https://github.com/cncf/toc/issues/471

**Pull request merged**
