### PR TITLE
Address comments in #71

### PR DESCRIPTION
**Pull request by caniszczyk**
https://github.com/cncf/toc/pull/71#issuecomment-350858244

cc: @bgrant0607 and @cncf/toc 

Let me know if you're happy with the wording, I'm flexible here.

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks. LGTM. Useful clarification. We can iterate further if necessary.

**Comment by jonboulle** [comment]
:+1: lgtm too

**Comment by skamille** [comment]
Part of the reason raised for inception-level projects was that the foundation provides some degree of legal shielding that allows developers from big companies to more easily collaborate. Is there value in calling that out after some fashion? Otherwise I'm starting to wonder why we really need inception-level projects for most initiatives, why have the foundation stamp of approval for the early glimmer of an idea, really, as per all the concerns on "organic" open source. The call for cultivating a "community" worries me from the king-maker perspective.

**Comment by bgrant0607** [comment]
Currently we don't really distinguish between incubation-level and inception-level projects in the way we treat them. I think we should. For instance, we shouldn't market inception-level projects as heavily, since they would presumably not be ready for hordes of new users. Another idea is a different "brand" for such projects.

**Comment by dankohn** [comment]
Once Kubernetes (and hopefully Prometheus) graduates, we had planned to
change the logos on https://www.cncf.io/ and in other media to feature
graduated projects biggest, incubating medium and inception smaller.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by monadic** [comment]
We absolutely MUST make it clear that inception projects are different, on the main pages of cncf.io.  I'd like to see language as well as graphics.

**Comment by jonboulle** [comment]
strong agreement on enhancing/clarifying the distinction between the project levels - we've let that go for too long. It's become pretty apparent that there's a lot more distinction being made by the TOC when evaluating projects for acceptance that isn't reflected in the "single" badge of approval.

**Comment by caniszczyk** [comment]
I'll leave this open until Friday, if I don't hear any objection from other @cncf/toc members, I'll merge this clarification in. In terms of differentiating the projects, that's a goal for early next year, from the projects website to the landscape.

**Pull request merged**
