### PR TITLE
wasmCloud 2022 Annual Review

### PR DESCRIPTION
**Pull request by brooksmtownsend**
This is based off of the [Sandbox Annual Review](https://github.com/cncf/toc/blob/master/process/sandbox-annual-review.md) process. 
- [x] Is your PR called: [Project name] [year] Annual Review?
- [x] Did you include a file for <year>-<project name>-annual.md?
- [x] Did you include a link to your project’s devstats page?
- [x] Did you include a link to your MAINTAINERS file?
- [x] What do you know about adoption? Is there an existing ADOPTERS file?
- [x] Did you include any previous goals?
- [x] Are your current goals listed?
- [x] Did you include requests from the CNCF?
- [x] Do you want to start the process for incubation? (This is a separate process) 
  - Noted in the annual review, we would like to start the incubation process as we meet all of the requirements.

### CODE REVIEW

**Comment by brooksmtownsend** [comment]
Hey @amye / @TheFoxAtWork, looking to see if there's anything else you need from us here for the annual review 😄 We just got pinged in https://github.com/wasmCloud/wasmCloud/issues/403 from the CLO monitor bot.

Separate question, do we need to do anything else to make sure the annual review shows on the landscape? Thank you.

**Comment by TheFoxAtWork** [comment]
@brooksmtownsend Apologies for the delay, we've got a number of annual reviews open and are finalizing the process to distribute assignment and completion among the TAGs with support from the Liaisons.

**Comment by Saim-Safdar** [comment]
Happy to be a reviewer.

**Comment by brooksmtownsend** [comment]
Hey folks, I noticed we deleted our repo and I wasn't aware this was still open. Are we okay to leave this closed?

**Comment by amye** [comment]
We should reopen, this doesn't appear to be touched.

**Comment by brooksmtownsend** [comment]
Reopened in #1197. Thanks @amye!

cc for awareness @TheFoxAtWork / @Saim-Safdar

**Comment by Saim-Safdar** [comment]
@brooksmtownsend is good to reopen, hasn't touched yet,

**Pull request closed without merging**
