### PR TITLE
Proposal: Move Pixie to Incubation

### PR DESCRIPTION
**Pull request by zasgar**
Hi ToC and CNCF community,

Pixie was accepted as a CNCF sandbox project in June 2021. Since our inclusion in the CNCF, Pixie has seen promising community contribution, growth, and adoption. We would like to take the next step towards incubation so we can better serve the broader CNCF community!

@aimichelle and @zasgar, will be the main contact points for this process. 

Thanks, 

The Pixie team

Signed-off-by: Zain Asgar <zasgar@pixielabs.ai>

### CODE REVIEW

**Comment by dmiyamasu** [comment]
Hooray Pixie!
🎉👍🏽

**Comment by halcyondude** [comment]
Pixie has [reached out TAG Observability in our (CNCF) slack channel](https://cloud-native.slack.com/archives/CTHCQKK7U/p1675454859199369) to announce this application, and has offered to present to the TAG as part of the application to Incubation. 

Reproducing relevant snippets here:

---

**Zain Asgar**
> Hi Folks!
> One of the [Pixie](https://px.dev/) maintainers here. We just submitted our proposal to move from [sandbox to incubation](https://github.com/cncf/toc/pull/1001). We’d love to present what we have been working on and get feedback from the group here. Let me know if that something the group is interested in. Thanks!

**Ken Finnigan**
> The group would definitely be interested in hearing the latest from Pixie. 
> [@Matt Young](https://cloud-native.slack.com/team/UPSTWGCBH) can help with arranging.

**Zain Asgar**

> Thanks 
> [@Ken Finnigan](https://cloud-native.slack.com/team/U01A5LP191A)!
> [@Matt Young](https://cloud-native.slack.com/team/UPSTWGCBH) great to reconnect with you! Let me know what works. We are supper happy to engage with the TAG.

**Amit Chaudhary**
> I used Pixie earlier, Felt it have some missing things. Would love to give it more try.

**Matt Young**
> Hi Zain!  Thanks for linking the application, I look forward to giving it a read.

> Let’s schedule time separately (announced, open, recorded, posted) for a formal presentation to the TAG as part of the Incubation Application Process.

> It’s been fantastic to have seen the growth of project since joining the sandbox. I’ll compile a list of links to your various updates to the TAG and post. We could just about make a playlist :headphones:

---

The Pixie project has regularly checked in with the TAG since joining the Sandbox. I'll follow up with the following as updates to this issue:

- [ ] list of links to Pixie's presentations over the years
- [ ] details on the pending presentation to TAG Observability
- [ ] a link to the video/presentation and slides

**Comment by TheFoxAtWork** [comment]
Quick update - about 2/3 thru the DD review. Hoping to wrap up in the next two weeks and move to active discussion with the project and then adopter interviews.

**Comment by TheFoxAtWork** [comment]
Wrapped up DD review, provided a few recommended clarifications to the project. Checked in with TAG CS who is conducting a [governance review](https://github.com/cncf/tag-contributor-strategy/issues/630) as a result of a recent significant improvement to the project's governance.
Kicking off adopter interview scheduling while discussing recommendations with the project.

**Comment by TheFoxAtWork** [comment]
Following up here: @zasgar @aimichelle , i reached out in Pixie slack but havent heard back yet, please provide additional adopters for interviews by June 11th.

**Comment by TheFoxAtWork** [comment]
Thank you @aimichelle for providing the additional adopters, i've reached out to them to coordinate scheduling.

**Comment by TheFoxAtWork** [comment]
### For the project:
The TOC has reviewed the project and determined it is not yet ready for incubation, the following areas were identified for resolution to enable the project to reapply at a later date. Depending on the length of time to complete these activities, the TOC may pick up the [Due Diligence](https://docs.google.com/document/d/1dy2EF_LsO54b8Ud6lJ4ll2dtBiN1URc7asZ1CLhnOZ0/edit) with slight refresh and round out the last adopter interviews.

Areas identified that would enable the project to reapply:

- ease the onboarding experience Pixie - we had limited feedback that becoming familiar enough with Pixie and Pxl was a challenge and required fair effort from Senior engineers to get going with adoption.
- make the project more approachable for users - we had limited feedback that there are two primary roles the project appeals most to, (SREs and backend engineers working with legacy and third party applications/APIs). However it is not readily discernible to potential adopters the value the project has to them for those particular roles (or other roles where applications and workloads may not be instrumented for telemetry)
- get more relevant adopters: ideally end users that leverage Pixie for centralized observability across their infrastructure

When the you are ready to reapply, please reference this PR and this comment so the next TOC sponsor may pick up with understanding of next steps.

### For the next TOC sponsor:
This project was submitted against the old process for moving levels, but was evaluated using the new criteria. Notes for that evaluation and the kick-off are in the TOC drive under Moving Levels Resources > 2024 Pixie Incubation DD. [2024 Due Diligence document may be found here](https://docs.google.com/document/d/1dy2EF_LsO54b8Ud6lJ4ll2dtBiN1URc7asZ1CLhnOZ0/edit).

**Comment by TheFoxAtWork** [comment]
Closing this application as not ready, reference previous comment for status and next steps.

**Comment by TheFoxAtWork** [comment]
Governance Review of Pixie, when the project is ready to reapply and a TOC sponsors steps forward to pick up where this was left off. https://github.com/cncf/tag-contributor-strategy/blob/main/governance/assessments/projects/pixie/2024-09-27.md

**Pull request closed without merging**
