### PR TITLE
in-toto proposal

### PR DESCRIPTION
**Pull request by SantiagoTorres**
Hi! 

this is the PR for the in-toto proposal into the CNCF. We aim to be adopted at the incubation level.

There's more information about the security review on the sig-security PR [here](https://github.com/cncf/sig-security/issues/166)

CC @caniszczyk  @JustinCappos @torresariass @michelleN

### CODE REVIEW

**Comment by rawkode** [comment]
I'm not a binding CNCF vote, but I think it's really cool there's an admission controller for in-toto; but I'm worried it's not seen any activity in 8 months.

**Comment by SantiagoTorres** [comment]
> I'm not a binding CNCF vote, but I think it's really cool there's an admission controller for in-toto

Yes! we're very excited to see more traction on it. 

> but I'm worried it's not seen any activity in 8 months.

Yes, it hasn't seen activity directly, yet a lot of action on the kubectl plugin translates directly to the webhook

**Comment by sublimino** [comment]
Stoked to see this here - @controlplaneio have been using in-toto with clients for the past year and it's a fantastic project :star2:

**Comment by trishankatdatadog** [comment]
Datadog has deployed TUF (another CNCF project) and in-toto in [production](https://www.datadoghq.com/blog/engineering/secure-publication-of-datadog-agent-integrations-with-tuf-and-in-toto/).

**Comment by mattklein123** [comment]
My personal opinion is that this project should start as sandbox. I don't obviously see the traction that IMO would qualify it for incubation. With that said, I am definitely supportive at sandbox.

**Comment by JustinCappos** [comment]
> My personal opinion is that this project should start as sandbox. I don't obviously see the traction that IMO would qualify it for incubation. With that said, I am definitely supportive at sandbox.

We'd be happy to provide more details about adoption to give a more complete picture.  Some of our adopters have clients that are banks and other organizations that will not allow us to publicly post their names in a thread like this.

Trishank at Datadog has said the most about their production use in a nice blog post.  I'm sure he'd be happy to discuss their users in more detail.

Andrew Martin at ControlPlane can give a lot of details about their user base and the importance of in-toto to them.

We also have a variety of folks at Debian, ArchLinux, etc. that we can loop in to provide more information.  There are also a lot of smaller adopters we can include if this is useful.

What is the best way to help you get the information you need to move forward?  Would you like us to set up a discussion with folks here to assist with your due diligence?

We've been through a long slog on the security assessment side and haven't been as focused on providing clear information about other topics the TOC looks at as we should have been.

If I recall, I think a TOC member had a question about our community stats too.  We can clarify anything else in the thread here that is desired.

**Comment by sublimino** [comment]
ControlPlane has shipped pipelines based around in-toto at three major organisations as part of SDLC hardening projects, but the customers cannot directly discuss these implementations. Further pipeline integrations are planned.

One concern I foresee with holding "security tooling" to the same adoption standards as "devops tooling" is the asymmetry of expected installations, users, contributors etc. Consider the number of (Dev)SecOps engineers vs DevOps in major organisations. 

As an individual's journey to security awareness comes after learning and hacking around other tooling, there will always be fewer users for something like in-toto than (to pick on the other projects in the same session) monitoring or VM tooling.

**Comment by caniszczyk** [comment]
FYI in-toto folks, @lizrice and @michelleN have agreed to sponsor the project at the sandbox level to start with the reminder that you don't have to be in the sandbox long as you become part of CNCF and work out your governance and public adopters. For example, Harbor started in CNCF as part of the sandbox and a few months later successfully applied for incubation.

**Comment by SantiagoTorres** [comment]
hi, @caniszczyk . Thanks for the FYI. 

I think we'd be happy to join into sandbox as long as there's a clear pathway forward. We'll work to improve all our governance documents and public adopters list asap, and would love to try moving towards incubation by, say, Kubecon NA?

Thanks!

**Comment by JustinCappos** [comment]
Yes, to reiterate Santiago's sentiment, we're happy to join as a sandbox project at this time.  We will be working hard to produce the needed documentation to move to incubation in the near future!

**Comment by michelleN** [comment]
awesome. Great to hear @JustinCappos @SantiagoTorres !
@caniszczyk - what are next steps for the in-toto folks? do they need to change the proposal? how should we proceed? thank you!

**Comment by caniszczyk** [comment]
@michelleN I'll update the proposal

I'll reach out to @SantiagoTorres and @JustinCappos to do the domain transfer and repo dance and get them fully onboarded as a sandbox project, thanks!

**Comment by michelleN** [comment]
awesome. thank you @caniszczyk

**Comment by caniszczyk** [comment]
Welcome in-toto to the CNCF Sandbox! :) We look forward to working with you over the next month to onboard you to the sandbox

**Pull request merged**
