### PR TITLE
Update DEFINITION.md

### PR DESCRIPTION
**Pull request by devsachinsharma**
Added definition in Hindi language.

Signed-off-by: Sachin Sharma <66516153+devsachinsharma@users.noreply.github.com>

### CODE REVIEW

**Comment by dims** [comment]
@divya-mohan0209 Can you please take a look? It looks good to me.

**Review by divya-mohan0209 — COMMENTED** [review]
Nit: I think we should arrange the listing in English alphabetical order 
The content looks good to me overall.

**Comment by dims** [comment]
thanks! @divya-mohan0209 for the purposes of this PR, let's leave it where it is. Someone can follow up with the re-ordering.

@amye LGTM as well, please merge.

**Comment by dims** [comment]
Also note that the google translate back into english looks very good as well.

image

**Comment by nikhita** [comment]
LGTM as well. Looks like this is good to go @amye :)

**Pull request merged**
