### PR TITLE
Network Service Mesh proposal as Sandbox project.

### PR DESCRIPTION
**Pull request by edwarnicke**

### CODE REVIEW

**Comment by caniszczyk** [comment]
thanks RFC @cncf/toc 

If there is a desire, we can schedule this for a presentation 2nd week of April (there are 2 TOC sponsors already)

**Comment by edwarnicke** [comment]
@caniszczyk @cncf/toc The Network Service Mesh community would love to do our review the 2nd week of April if that is convenient for the TOC 👍

**Comment by caniszczyk** [comment]
Hey @jbeda and @mattklein123 can you confirm here you're OK sponsoring this project?

Thanks

**Comment by jbeda** [comment]
Confirmed!

**Comment by mattklein123** [comment]
Confirmed!

**Comment by caniszczyk** [comment]
Thanks! NSM is now in the sandbox

**Pull request merged**
