### PR TITLE
Propose Longhorn into CNCF Sandbox

### PR DESCRIPTION
**Pull request by yasker**
Hi,

This PR proposes Longhorn into CNCF Sandbox.

Longhorn is an open source distributed block storage software for Kubernetes. It is a lightweight and portable implementation of persistent storage that works for any Kubernetes cluster. The project implements distributed block device volumes that can be mounted as read-write by a single node (ReadWriteOnce).

Longhorn currently have [600+ stars](https://github.com/longhorn/longhorn/stargazers) on GitHub.

### CODE REVIEW

**Comment by caniszczyk** [comment]
RFC @cncf/toc

**Comment by caniszczyk** [comment]
Hey @lizrice and @monadic can you confirm that you're OK sponsoring this project

**Comment by lizrice** [comment]
I am interested in sponsoring. I would like to see the TOC presentation (which I believe is planned for July 9) before signing off.

**Comment by andyjeffries** [comment]
Definitely a huge fan of this. We wrote a post on how to use it last week and it's an incredible project that could do with the visibility and support that being a CNCF sandbox project will bring. https://www.civo.com/learn/cloud-native-stateful-storage-for-kubernetes-with-rancher-labs-longhorn

**Comment by smw355** [comment]
Really excited to see Longhorn go into the CNCF. Storage is a fantastic area for the CNCF to support and invest in developing some strong open source options for the market.

**Comment by jbeda** [comment]
Some concerns here:
* There are no contribution guidelines.
* Unclear if/how many non-rancher folks have contributed. Not a blocker but something to look at.
* There doesn't appear to be any DCO or CLA implemented.  This is something that would need to be resolved.

**Comment by yasker** [comment]
@jbeda Thanks for the comment! We will get this resolved soon.

**Comment by jbeda** [comment]
Looks like Sheng did a great job addressing the procedural issues that I brought up above.  There is now a DCO enforcement bot for forward looking commits, contributing guidelines, CoC, etc.  Great start to making it more community driven and welcoming!

(I was just looking at the longhorn/longhorn repo.  Still some busywork to do in terms of getting things lined up in the other repos but it isn't blocking IMO.)

Note: I'm not ready to sign on as supporting as I haven't had the time to dig deep and won't for a week or two. But I don't want these concrete issues to stand in the way of others.

**Comment by yasker** [comment]
Thanks @jbeda !

**Comment by lizrice** [comment]
Confirming that I am happy to sponsor Longhorn to Sandbox. @monadic?

**Comment by monadic** [comment]
Confirmed that I am happy to sponsor Longhorn to Sandbox.

**Comment by yasker** [comment]
Thank you @lizrice @monadic !

**Comment by amye** [comment]
@caniszczyk, we are good to move forward on this.

**Comment by caniszczyk** [comment]
I'll get this done by Wednesday and work with @yasker to get everything transferred over

**Comment by amye** [comment]
Perfect, thank you.

On Mon, Oct 7, 2019 at 10:30 AM Chris Aniszczyk
<notifications@github.com> wrote:
>
> I'll get this done by Wednesday and work with @yasker to get everything transferred over
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Amye Scavarda Perrin | Program Manager, CNCF | amye@linuxfoundation.org

**Comment by yasker** [comment]
Thanks @caniszczyk , let me know what you would need.

**Comment by caniszczyk** [comment]
Welcome Longhorn to the CNCF Sandbox, we will be working with them over the next week to transfer assets and get them setup with the service desk!

**Pull request merged**
