### PR TITLE
Tinkerbell 2022 Annual Review

### PR DESCRIPTION
**Pull request by jacobweinstock**
Hello! This PR is for the Tinkerbell project's 2022 annual review. Thank you!

### CODE REVIEW

**Comment by jacobweinstock** [comment]
Hello there! I wanted to see if anyone could tell me if the Tinkerbell project has submitted all the appropriate items for the annual review? I ask because I have received [multiple notifications](https://github.com/tinkerbell/tink/issues/741#issuecomment-1655863705) from the [clomonitor-bot](https://github.com/clomonitor-bot), after this PR was opened and labeled) reminding me that the annual report is due. Apologies if this is not the appropriate forum to ask these questions.

**Comment by nikhita** [comment]
@jacobweinstock apologies for the delay in reviews here! We've got a number of annual review PRs open, and are now [finalizing](https://lists.cncf.io/g/cncf-toc/message/8183) the process to distribute assignment and completion among the TAGs with support from the TOC Liaisons.

This PR should get reviewed soon 👍

**Review by cathyhongzhang — CHANGES_REQUESTED** [review]
Could you provide the information on the community growth, such as the number of new maintainers or contributors?  Do you have regular open project meetings? Could you attach meeting notes showing attendees?

**Comment by jacobweinstock** [comment]
> Could you provide the information on the community growth, such as the number of new maintainers or contributors? Do you have regular open project meetings? Could you attach meeting notes showing attendees?

Hi @cathyhongzhang, sure thing. I hope this will suffice.

- For this annual report Tinkerbell's maintainers were documented [here](https://github.com/cncf/toc/blob/a4bf6ff3a62e3a183d1f59d3ae36adabba56338f/reviews/sandbox/2022/2022-Tinkerbell-annual.md#maintainers). This is our first annual report so we dont have any historical data with which to compare. 
- Among other locations contributor contributions can be seen here: [devstats](https://tinkerbell.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1), [slack channel](https://cloud-native.slack.com/archives/C01SRB41GMT). We don't keep an explicit records of new contributors but I imagine this info can be extrapolated from devstats or from our releases page in each repo.
- We meet weekly on Tuesdays at 3pm UTC. Every other week is a recorded and agenda driven meeting and the other week is an open forum meeting. The agenda with notes and etc for the agenda meeting can be found [here](https://docs.google.com/document/d/1Hmqrhj2rPjZ5W0DvRynFNY2cJq6jFCbNOc4p26U5Dgg/edit?usp=sharing)

**Review by cathyhongzhang — APPROVED** [review]

**Pull request merged**
