### PR TITLE
Pravega 2022 annual review

### PR DESCRIPTION
**Pull request by RaulGracia**
Pravega annual review as per [CNCF TOC guidelines](https://github.com/cncf/toc/blob/main/process/sandbox-annual-review.md#how-to-file-your-annual-review).

Fixes https://github.com/pravega/pravega/issues/7097

### CODE REVIEW

**Comment by RaulGracia** [comment]
Thanks @amye, is the `clomonitor-bot` that posted a friendly reminder in issue https://github.com/pravega/pravega/issues/7097.
If that is expected, then I'm fine with it. Thanks!

**Comment by amye** [comment]
Yep, expected behavior! Clomonitor is our new reminder tool for this.

**Comment by yasker** [comment]
FYI: I will be reviewing this on behave of TAG Storage.

**Comment by yasker** [comment]
On behave of TAG Storage:

Pravega has demonstrated continued and ongoing progress toward the scope it has mandated in its annual review. It also has an appropriate project governance structure that follows CNCF guidelines. Pravega recognizes several outstanding items before they are ready for incubation:
* Community presence seems limited in the public.
* Adoption seems limited outside of the main sponsor company. 
* The roadmap has not been updated to reflect the long-term plan of the project.

Following are some suggested remediations that should be taken. Maintainers should reach out to TAG storage within 6 months to present an update on the remediations taken:
* Increase the community presence.
    * Make Slack channel available to the public. 
    * Organize routine community meetings
* Increase the adoption outside the main sponsor company
* Keep the roadmap up to date with the new releases.

cc @xing-yang @nikhita

**Comment by RaulGracia** [comment]
Dear @yasker,

Thanks a lot for your feedback. We have worked in the last weeks to implement the suggested remediations to continue growing the project:
1. `Increase the community presence.`:
1.1. We have done the changes in the website (e.g., footer links) to use a public link for joining Slack. We have also changed the "Join the Community" page to use the same public Slack link and also adding the Twitter account (https://github.com/pravega/pravega/pull/7297). You can see the result of this change in the "nightly" version of the documentation, that will become the default one in the next release: https://cncf.pravega.io/docs/v0.14.0-SNAPSHOT/join-community/
1.2. We have resumed our community meetings and agreed to organize them in a bi-monthly cadence at the moment. We organized the November Community meeting (https://community.cncf.io/events/details/cncf-pravega-community-presents-pravega-community-meeting-2/) and the next one is planned in January.
1.3 We also attended Kubecon'23 in Shanghai (https://x.com/PravegaIO/status/1709234826304209190?s=20) and we are planning to attend Kubecon'24 in Paris.

2. `Increase the adoption outside the main sponsor company`:
2.1. We are involved in 2 new European Research projects (https://neardata.eu/, https://cloudskin.eu/) in which Pravega is a key technology for streaming. This will help us to expose Pravega to a network of +20 partners, including large companies and research institutions across Europe. This will contribute to the adoption of Pravega beyond the main sponsor company and its own customers. More details can be found in this blog post: https://cncf.pravega.io/blog/2023/06/06/pravega-in-european-research-projects/
2.2. We have also published two scientific papers about Pravega in ACM/IFIP Middleware (https://middleware-conf.github.io/2023/). We expect with this effort to broaden the adoption of Pravega across the scientific and research community.

3. `Keep the roadmap up to date with the new releases.`:
3.1 The steering committee of the project has met to provide a simplified and updated view of the project roadmap (https://github.com/pravega/pravega/pull/7320). Again, this is available currently in the "nightly" documentation (https://cncf.pravega.io/docs/v0.14.0-SNAPSHOT/roadmap/) and will be the default roadmap page in the next release.

Please, let us know if these action items have addressed your comments.
Thanks!

cc/ @fpj @tkaitchuck

**Comment by TheFoxAtWork** [comment]
@mattfarina & @nikhita as Liaisons for TAG Storage, would you review/approve/merge?

**Comment by amye** [comment]
Marking this as complete, annual reviews are no longer a requirement for sandbox. 
We'll be rolling out more efficient ways to show project health and metrics in 2024.

**Pull request merged**
