### PR TITLE
Vitess graduation proposal

### PR DESCRIPTION
**Pull request by morgo**
This is a proposal to consider Vitess for CNCF graduation.

I have included answers for both incubation and graduation requirements. Answers to [Due Dilligence questions](https://docs.google.com/document/d/1TDlRdgfTiEWunpav-G8gkaQF7Zk84-9tNAXyv1I0Kws/edit) are also available in Google Docs.

Please let me know if anything is missing or can be clarified further.

### CODE REVIEW

**Comment by amye** [comment]
Happy to schedule with you for a TOC presentation, we have space in our October 15th meeting.

**Comment by morgo** [comment]
@amye This date works for us. Thank you!

**Comment by amye** [comment]
Great! Catch up with me at amye@linuxfoundation.org and I'll give you access to post slides for that 10/15 meeting.

**Comment by caniszczyk** [comment]
@xiang90 has agree to do the due diligence

**Comment by xiang90** [comment]
@caniszczyk 

I reviewed the DD for Vitess. Here is the doc: https://docs.google.com/document/d/1TDlRdgfTiEWunpav-G8gkaQF7Zk84-9tNAXyv1I0Kws/edit?ts=5da8eafc#heading=h.nu2qbsaqadff

Looks good in general. There were a couple of small issues, the team quickly fixed them. 

If other TOC are OK with the DD, I think it is ready for a graduation vote.

**Comment by caniszczyk** [comment]
Thanks @xiang90, heads up @cncf/toc,  we will call a vote early next week

**Comment by caniszczyk** [comment]
+1 binding TOC votes (6/9):
Matt Klein: https://lists.cncf.io/g/cncf-toc/message/3689
Brendan Burns: https://lists.cncf.io/g/cncf-toc/message/3693
Joe Beda: https://lists.cncf.io/g/cncf-toc/message/3697
Xiang Li: https://lists.cncf.io/g/cncf-toc/message/3703
Jeff Brewer: https://lists.cncf.io/g/cncf-toc/message/3708
Liz Rice: https://lists.cncf.io/g/cncf-toc/message/3715

https://www.cncf.io/announcement/2019/11/05/cloud-native-computing-foundation-announces-vitess-graduation/

**Pull request merged**
