### PR TITLE
Open Cluster Management 2022 Annual Review.

### PR DESCRIPTION
**Pull request by mikeshng**
Signed-off-by: Mike Ng <ming@redhat.com>

### CODE REVIEW

**Comment by mikeshng** [comment]
CC @qiujian16

**Comment by akhilerm** [comment]
I will be doing the review of this PR.

@nikhita can you please assign it to me.

**Comment by raravena80** [comment]
@akhilerm following up with the review? Were you able to complete it?

Thanks!

**Comment by akhilerm** [comment]
Yes. There was one pending comment related to rearranging some maintainer info. I have resolved it.

cc: @RichiH Can you do the final review of the doc as the TOC Liaison.

**Comment by raravena80** [comment]
Here's the [doc link](https://docs.google.com/document/d/19vOb_E0WxB3mXFoBZ0sDsX1dZx6_dRUTFEb_hFVnEzU/edit) to the review.

**Comment by TheFoxAtWork** [comment]
@nikhita @RichiH @cathyhongzhang please review the linked comment/recommendation from the TAG and provide concurrence/approval.

**Comment by amye** [comment]
Marking this as complete, annual reviews are no longer a requirement for sandbox. 
We'll be rolling out more efficient ways to show project health and metrics in 2024.

**Pull request merged**
