### PR TITLE
Proposing CubeFS for graduation

### PR DESCRIPTION
**Pull request by leonrayang**
This is a formal proposal to consider CubeFS for CNCF graduation.

CubeFS is an open-source project that joined CNCF as a sandbox project in December 2019, has made remarkable progress since then. With its growing community of contributors and users including big names like Oppo, JD, Xiaomi, NetEase, and BIGO, CubeFS has already scaled up to hundreds of petabytes (PB+). As of July 2022, CubeFS has become an incubating project and we are confident that it is now ready to graduate.

In this PR you can find the proposal document that highlights how CubeFS has met the graduation criteria as defined by CNCF.

Please kindly inform me if there is anything missing or if further clarification is required.

* [CubeFS Governance Checklist](https://github.com/cubefs/cubefs/issues/3298)

#### Link to Graduation Due Diligence(DD) Document
* [CubeFS Due Diligence(This one is an old version; The sponsor is helping to build it according to the new rules.)](https://docs.google.com/document/d/1gMmRMhO1JkZzo6znxlnNpme11MRqjD9v-yR5Cq-oo28/edit#heading=h.560y4815aj5r)

#### Link to Incubation Due Diligence(DD) Document
* [Incubation proposal](https://github.com/cncf/toc/pull/586)
* [CubeFS Due Diligence](https://docs.google.com/document/d/1WDJEeRDO8pHAetyCbU7TftZfvxSATc3bsLj7VJeNoJ0/edit#heading=h.560y4815aj5r)

#### Link to CubeFS Security Audit
* [CubeFS Security Audit](https://github.com/cubefs/cubefs/blob/master/security/CubeFS-security-audit-2023-report.pdf)

### CODE REVIEW

**Comment by nikhita** [comment]
@leonrayang thanks for creating the PR!

Can you also present an update to TAG Storage? That'll help with the Graduation proposal.

**Comment by sonasingh46** [comment]
+1 to what @nikhita said. 
We have TAG Storage meetings on Aug 9 and Aug 23. Let us know if you want to present at either of these meetings. Also, [this](https://cloud-native.slack.com/archives/C6PK4RLF7/p1690353785171519) is a similar thread which can help you prepare for the presentation.

**Comment by humblec** [comment]
@leonrayang its also good to mention the incubation proposal ..etc in the PR description for quick reference.

**Comment by leonrayang** [comment]
> @leonrayang thanks for creating the PR!
> 
> Can you also present an update to TAG Storage? That'll help with the Graduation proposal.

Thank you for the reminder. Yes, we are currently in the process of preparing.

**Comment by leonrayang** [comment]
> 

Thank you for the reminder. I think August 23rd works fine.

**Comment by sonasingh46** [comment]
@leonrayang - Sure. I have added CubeFS presentation in the meeting agenda.

**Comment by xing-yang** [comment]
@leonrayang Has CubeFS completed an independent third-party security audit?

**Comment by leonrayang** [comment]
> @leonrayang Has CubeFS completed an independent third-party security audit?

OSTIF staff has already arranged a team to conduct an audit for CubeFS, and they have started the related auditing work. It is expected to take some time to complete the audit. OSTIF mentioned that we can proceed with other graduation matters in parallel with the security audit. The goal is to have the security audit completed before the official graduation. Is that correct?

**Comment by leonrayang** [comment]
@caniszczyk,We kindly request CNCF to provide a sponsor to support the graduation application of CubeFS. There are many procedures related to graduation, and we need more assistance. Thank you.

**Comment by amye** [comment]
A TOC sponsor will step forward if they have capacity and are interested!

**Comment by xiaochunhe** [comment]
> A TOC sponsor will step forward if they have capacity and are interested!

hi，amye，is there any TOC sponsor interested in cubefs? without a sponsor, we cannot promote presentation at TAG meetings

**Comment by craigbox** [comment]
> hi，amye，is there any TOC sponsor interested in cubefs? without a sponsor, we cannot promote presentation at TAG meetings

Did someone tell you this?  [Giving a presentation is a requirement in the new checklist](https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-incubation-application.md), so I hope that this presentation is not be gated on having been assigned a sponsor.

**Comment by xing-yang** [comment]
Thanks CubeFS team for giving a project update at TAG Storage meeting on 4/24!
Here's the meeting recording: https://www.youtube.com/watch?v=UgRBZhzfr4w
Here are the slides: https://docs.google.com/presentation/d/18gqQ6X8cpdASQ5JaGUJb0otQDZSWM1p_/edit?usp=sharing&ouid=101542329241571091448&rtpof=true&sd=true
cc @chira001 & Raffaele Spazzoli

**Comment by kevin-wangzefeng** [comment]
Status update for CubeFS graduation:
1. The CubeFS maintainers and I had a kick-off meeting on Apr. 10th and a few more meetings afterwards.
2. The CubeFS team has provided information according to latest graduation template at https://github.com/cubefs/cubefs/issues/3298
3. I've finished initial review of the input from maintainers and now diving deep into more details, no blocing issues found so far.
4. Suggested actions (may add more later on):
    - [ ] Provide an adopter interview candidate list, would be nice if with 5-7 across multiple verticals( ref: https://github.com/cubefs/cubefs/blob/master/ADOPTERS.md)
    - [ ] Reach out for TAG assessment:
      - [x] TAG-storage, for domain specific technical review
      - [ ] TAG-Contrib-Strategy, to compelet governance review
    - [ ] Document the Roadmap change process as part of the governance
    - [ ] Update the release process to reflect the latest shift to CNCF infrastructure (ref: https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-graduation-application.md?plain=1#L190-L197)

**Comment by kevin-wangzefeng** [comment]
Updated status to "Active Review & Discussion" in the TOC Board.

**Comment by kevin-wangzefeng** [comment]
@xing-yang @chira001 @raffaelespazzoli
Could you help to provide the recommendation from TAG-storage? Thanks

**Comment by leonrayang** [comment]
> Status update for CubeFS graduation:
> 
> 1. The CubeFS maintainers and I had a kick-off meeting on Apr. 10th and a few more meetings afterwards.
> 2. The CubeFS team has provided information according to latest graduation template at [[Enhancement]: cncf graduation checklist cubefs/cubefs#3298](https://github.com/cubefs/cubefs/issues/3298)
> 3. I've finished initial review of the input from maintainers and now diving deep into more details, no blocing issues found so far.
> 4. Suggested actions (may add more later on):
>    
>    * [x]  Provide an adopter interview candidate list, would be nice if with 5-7 across multiple verticals( ref: https://github.com/cubefs/cubefs/blob/master/ADOPTERS.md)
>    * [ ]  Reach out for TAG assessment:
>      
>      * [x]  TAG-storage, for domain specific technical review
>      * [ ]  TAG-Contrib-Strategy, to compelet governance review
>    * [x]  Document the Roadmap change process as part of the governance
>    * [x]  Update the release process and guidelines to reflect the latest engineering principles criteria (ref: https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-graduation-application.md?plain=1#L190-L197)

@kevin-wangzefeng The checklist already updated  [[Enhancement]: cncf graduation checklist cubefs/cubefs#3298](https://github.com/cubefs/cubefs/issues/3298) ，I have marked the completed section of the suggested actions here

**Comment by kevin-wangzefeng** [comment]
Status update:
  - [ ] Due diligence report: progress 95%
    - Most of the content has been finished, now finalizing the summary, part, and adopters part, WIP draft at: https://github.com/kevin-wangzefeng/toc/blob/cubefs-graduation/proposals/graduation/cubefs-graduation-dd.md
  - [ ] Adopter interview: progress 97%
    - I've finished all the adopter inteview, and now confirming with the interviewees for final approval
  - [ ] Reach out for TAG assessment:
    - [x] TAG-storage, for domain specific technical review.
	  - TAG-Storage has provided their recommendation at https://docs.google.com/document/d/1D-Y1XVmPNu_g4Vtl6ZhmueR2ATmuGjoe8Bnc-uTFsqI/edit#heading=h.i6nawr9zumuc, thanks @xing-yang
    - [ ] TAG-Contrib-Strategy, for governance review
      - Governance review by TAG-Contrib-Strategy looks still on going, initial report is at: https://docs.google.com/document/d/1xd8hCw0O-RiotwO5A046UFU1l_9XLhDK2ZxfVAUa0rg/edit#heading=h.xzd1hltrr2sq, @aliok please feel free to provide updates, thanks
  - [x] Document the Roadmap change process as part of the governance
      - fixed by the project team, details will be recorded in the DD report
  - [x] Update the release process to reflect the latest shift to CNCF infrastructure (ref: https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-graduation-application.md?plain=1#L190-L197)
      - fixed by the project team, details will be recorded in the DD report

**Comment by TheFoxAtWork** [comment]
@kevin-wangzefeng  are we okay to close this PR in favor of #1473 ?

**Comment by kevin-wangzefeng** [comment]
> @kevin-wangzefeng are we okay to close this PR in favor of #1473 ?

It looks a bit duplicated that we have two items on the TOC Board for a same purpose.
The unclear part is whether we take this one as the tracking issue or switch to the DD PR instead, when it's ready.

We can probably keep this one open until whole process finished: there's an "In Press Coordination" period after voting. :-)

**Comment by kevin-wangzefeng** [comment]
Status update:
Thanks to everyone that helped with the review. The graduation of CubeFS is now ready for public comments, the period will keep open until Dec 8, 2024 (2 weeks starting from today).
Please feel free to chime in before we moving to a TOC vote.

DD PR: https://github.com/cncf/toc/pull/1473
Public Comment email notification: https://lists.cncf.io/g/cncf-toc/message/8730

**Comment by angellk** [comment]
TOC vote is open:
https://github.com/cncf/toc/pull/1473#issuecomment-2526194135

cc: @kevin-wangzefeng

**Comment by angellk** [comment]
**Congratulations** to the CubeFS community! The TOC vote passed - #1473 - and @mrbobbytables is added to this PR for press coordination.

**Comment by leonrayang** [comment]
Thanks to @angellk @kevin-wangzefeng , and thanks to all the contributors who have participated in the project construction. Let's continue to move forward with efforts.

**Pull request merged**
