### PR TITLE
What: Adopter questions update

### PR DESCRIPTION
**Pull request by TheFoxAtWork**
Why:
 * Several TOC members have expanded the question set from past DDs

This change address the need by:
 * incorporating those additional questions
 * restructure the ordering for better flow

### CODE REVIEW

**Comment by rochaporto** [comment]
@TheFoxAtWork i see no updates in this PR?

**Comment by TheFoxAtWork** [comment]
now to find where the file went... thanks for the call out @rochaporto

**Comment by TheFoxAtWork** [comment]
@rochaporto okay now its fixed. its 3 additional questions plus reordering. thank you for catching it.

**Review by angellk — APPROVED** [review]
Thanks @TheFoxAtWork - lgtm. Captures what we discussed at the TOC offsite and TOC+TAB meeting.

**Pull request merged**
