### PR TITLE
Proposal: OpenTelemetry to join CNCF

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
We plan to present this proposal at the TOC meeting tomorrow.

Also by @bhs, @bogdandrutu, @sarahnovotny, @yurishkuro

/CC: @brendandburns, @bgrant0607, @mattklein123

/CC: @mtwo

### CODE REVIEW

**Comment by caniszczyk** [comment]
RFC @cncf/toc

**Comment by leecalcote** [comment]
With the sunsetting of OpenTracing (and OpenCensus), does this include archival of OpenTracing as a CNCF project?

**Comment by SergeyKanzhelev** [comment]
> With the sunsetting of OpenTracing (and OpenCensus), does this include archival of OpenTracing as a CNCF project?

The idea is to archive it once Open Telemetry will get into the incubation level. We have a tight schedule for sunsetting of Open Tracing and Open Census so the hope is that this will happen soon

**Comment by caniszczyk** [comment]
OpenTelemetry presented at the TOC meeting today and enters the CNCF sandbox, sponsored by Brendan Burns, Brian Grant, Matt Klein

**Comment by leecalcote** [comment]
The formation and acceptance of OpenTelemetry is a major win.

**Pull request merged**
