### PR TITLE
ChaosBlade 2022 Annual Review

### PR DESCRIPTION
**Pull request by MandssS**
The ChaosBlade annual report submitted on behalf of maintainers.

Signed-off-by: caimingxia <mingshao.cmx@alibaba-inc.com>

### CODE REVIEW

**Comment by MandssS** [comment]
ChaosBlade is a Sandbox project that was accepted to CNCF on April 27th, 2021.

Per the request of TOC, this is our annual review for 2022. @amye @leecalcote 

cc @fitzthum @magowan @ariel-adam @larrydewey @bpradipt

**Comment by MandssS** [comment]
When will this pr be merged?

**Comment by TheFoxAtWork** [comment]
This will be reviewed and completed by the end of the year, apologies for the delay.

**Comment by PushkarJ** [comment]
TOC, Please remove label for tag-security as we were unable to complete the review of the PR by Jan 1 deadline.

**Comment by amye** [comment]
Marking this as complete, annual reviews are no longer a requirement for sandbox. 
We'll be rolling out more efficient ways to show project health and metrics in 2024.

**Pull request merged**
