### PR TITLE
Weave Cortex Sandbox proposal

### PR DESCRIPTION
**Pull request by bcotton**
Please review and comment. Thanks!

### CODE REVIEW

**Comment by caniszczyk** [comment]
RFC @cncf/toc also the sandbox project is still seeking TOC sponsors

We will also bring this up on the call next week to review.

**Comment by caniszczyk** [comment]
Bryan Cantrill is on board to sponsor:

https://lists.cncf.io/g/cncf-toc/topic/feedback_on_cortex/21334154?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,21334154

**Comment by kenowens12** [comment]
I would be happy to serve as second TOC sponsor. Had a great conversation with project today,

**Comment by caniszczyk** [comment]
welcome Cortex to the CNCF sandbox :)

https://www.cncf.io/blog/2018/09/20/cncf-to-host-cortex-in-the-sandbox/

**Pull request merged**
