### PR TITLE
Incubation review for Rook

### PR DESCRIPTION
**Pull request by jbw976**
This pull request is to serve as a review for the proposal to graduate Rook from the Sandbox stage to the Incubating stage, tracked by #126.

[Jared Watts](https://github.com/jbw976) is planning to present to the TOC on August 21st.  Early feedback welcome in this PR.

### CODE REVIEW

**Comment by caniszczyk** [comment]
This deck contains more details: https://docs.google.com/presentation/d/1DOgAlX0RyB8hzD7KbmXK4pKu9hFFPY9WiLv-LEy38jo/edit

RFC @cncf/toc

**Comment by quinton-hoole** [comment]
LGTM.  Rook appears to adequately fulfill all of the requirements of CNCF incubation level projects.

**Comment by caniszczyk** [comment]
Rook has passed and has enough votes from the @cncf/toc to move to incubation

Alexis: https://lists.cncf.io/g/cncf-toc/message/2368
Ken: https://lists.cncf.io/g/cncf-toc/message/2371
Ben: https://lists.cncf.io/g/cncf-toc/message/2375
Quinton: https://lists.cncf.io/g/cncf-toc/message/2377
Sam: https://lists.cncf.io/g/cncf-toc/message/2390
Jon: https://lists.cncf.io/g/cncf-toc/message/2395

**Comment by caniszczyk** [comment]
https://www.cncf.io/blog/2018/09/25/toc-votes-to-move-rook/

**Pull request merged**
