### PR TITLE
Telepresence project proposal

### PR DESCRIPTION
**Pull request by richarddli**
Please review and comment. Thanks!

### CODE REVIEW

**Comment by caniszczyk** [comment]
Thanks, I'll have the @cncf/toc RFC and confirm sponsorship here, we should be able to get this settled by the TOC meeting next week.

**Comment by caniszczyk** [comment]
can @monadic and @skamille confirm their sponsorship here on this PR?

other than that, we are good to move forward

**Comment by richarddli** [comment]
Can we get set up with a CircleCI account for Telepresence? (We use it now for Telepresence, and we're going to have to update CI anyway with the move.)

**Comment by richarddli** [comment]
OK, I created github.com/telepresenceio and invited you. We're working on the website. cc: @kelseyevans

**Comment by caniszczyk** [comment]
Awesome, set for https://github.com/telepresenceio thanks

I'll email you for the domain transfer dance

**Comment by caniszczyk** [comment]
CNCF has the domain now, just need to do a review of the website and we'll be good to go

**Comment by richarddli** [comment]
The GitHub has been moved; CircleCI and Netlify has been updated. Can you put the CircleCI telepresenceio account under CNCF? 

The website has been changed with the CNCF logo, etc. Let me know if there's anything else.

**Comment by richarddli** [comment]
OK, website changes are done

**Pull request merged**
