### PR TITLE
Adding KNative to incubation

### PR DESCRIPTION
**Pull request by amye**

### CODE REVIEW

**Comment by jeefy** [comment]
lgtm!

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
LGTM

**Comment by caniszczyk** [comment]
this obviously passed!

https://lists.cncf.io/g/cncf-toc/message/6625
8/11
Dave Zolotusky: https://lists.cncf.io/g/cncf-toc/message/6626
Davanum Srinivas: https://lists.cncf.io/g/cncf-toc/message/6627
Emily Fox: https://lists.cncf.io/g/cncf-toc/message/6629
Alena Prokharchyk: https://lists.cncf.io/g/cncf-toc/message/6634
Ricardo Rocha: https://lists.cncf.io/g/cncf-toc/message/6635
Justin Cormack: https://lists.cncf.io/g/cncf-toc/message/6658
Matt Farina: https://lists.cncf.io/g/cncf-toc/message/6659
Lei Zhang: https://lists.cncf.io/g/cncf-toc/message/6666

**Pull request merged**
