### PR TITLE
add preferred maturity level to proposal requirements

### PR DESCRIPTION
**Pull request by jonboulle**

### CODE REVIEW

**Comment by jonboulle** [comment]
fixes #24

**Comment by caniszczyk** [comment]
+1 but lets get 2/3 of the @cncf/toc to +1 this

**Comment by bgrant0607** [comment]
+1

**Comment by jonboulle** [comment]
bump @cncf/toc

**Comment by bgrant0607** [comment]
@jonboulle @caniszczyk I suggest bouncing this to the mailing list if you expect responses. Github notifications are virtually worthless for busy people, and not all of the TOC is in that github team.

**Comment by bgrant0607** [comment]
But I also think we should just merge this.

**Comment by bgrant0607** [comment]
LGTM

**Comment by jonboulle** [comment]
@bgrant0607 somehow it got to you :-)

**Comment by bgrant0607** [comment]
@jonboulle Somehow made it through my filter.

**Pull request merged**
