### PR TITLE
Proposal: Longhorn to incubation

### PR DESCRIPTION
**Pull request by yasker**
Hi TOC members,

Longhorn joined CNCF one year ago. With the team's hard work and CNCF's help, we've seen tremendous growth in the Longhorn community in just one year. We think it's time to consider Longhorn for the incubation stage. 

Thanks.

### CODE REVIEW

**Comment by amye** [comment]
Next step is to have SIG Storage review the project. Has this been scheduled yet?

**Comment by yasker** [comment]
@amye Thanks for following up. No, the review hasn't been scheduled yet.

**Comment by amye** [comment]
It's a little fast, but they have a meeting on October 28th if you're ready to present. 
Alternatively, November 11th is also open.

**Comment by yasker** [comment]
@amye I am ready to present at either meeting. Thanks.

**Comment by yasker** [comment]
Update: I have presented Longhorn at SIG Storage meeting today. Waiting for the feedback from SIG Storage.

**Comment by saad-ali** [comment]
I've asked CNCF SIG Storage to start a Due Diligence doc for Longhorn based on the template for the DD doc [here](https://github.com/cncf/toc/blob/main/process/dd-review-template.md). 

One important question that the doc should address is how this project differs from other SDS solutions under the CNCF umbrella, e.g. OpenEBS and Rook/Ceph?

Alex, could you please help drive this?
/assign @chira001

**Comment by chira001** [comment]
> I've asked CNCF SIG Storage to start a Due Diligence doc for Longhorn based on the template for the DD doc [here](https://github.com/cncf/toc/blob/main/process/dd-review-template.md).
> 
> One important question that the doc should address is how this project differs from other SDS solutions under the CNCF umbrella, e.g. OpenEBS and Rook/Ceph?
> 
> Alex, could you please help drive this?
> /assign @chira001

Hi Saad - Luis and I will work on this - will schedule a kickoff call shortly - thanks for the nudge.

**Comment by saad-ali** [comment]
Awesome, thank you both!

**Comment by saad-ali** [comment]
The Due Diligence document for Longhorn has been completed and can be found [here](https://docs.google.com/document/d/1fimxaJ3sgc_q9_qtwoQhLo0RwxI6U_FnxyxAXfslKdE/edit#heading=h.rg1aev97ao2c). Thank you TAG Storage, @lpabon, @yasker, and @chira001 for that.

I am opening the two week public comment period now. https://lists.cncf.io/g/cncf-toc/message/6227

**Comment by saad-ali** [comment]
Two week public comment period is now complete with no objections. We will move to a vote on the TOC mailing list.

**Pull request merged**
