### PR TITLE
Update DEFINITION.md

### PR DESCRIPTION
**Pull request by atulkamble**
Added Marathi Definition for cloud native.

### CODE REVIEW

**Comment by Riaankl** [comment]
Can you please also ask another member of the Marathi cloud native community to review and agree on the meaning and grammar of the translation.

**Comment by TheFoxAtWork** [comment]
@atulkamble the cloud native definition was updated in february, if you could update the translation and identify another member of the Marathi community to review and concur it would be greatly appreciated.

**Review by kaiwalyakoparkar — APPROVED** [review]
Hey @riaankleinhans @TheFoxAtWork I am a Marathi speaker and this look good to me

**Comment by riaankleinhans** [comment]
> Hey @riaankleinhans @TheFoxAtWork I am a Marathi speaker and this look good to me

Thank you @kaiwalyakoparkar

**Comment by riaankleinhans** [comment]
@atulkamble we received a review of you update.

Can you please update the translation as requested above by @TheFoxAtWork and then request a quick review from @kaiwalyakoparkar

**Comment by mrbobbytables** [comment]
Closing due to lack of activity, we can reopen potentially later.

**Comment by atulkamble** [comment]
deleted branch patch-1

**Pull request closed without merging**
