### PR TITLE
ChubaoFS proposal for CNCF Sandbox

### PR DESCRIPTION
**Pull request by wding109**
Signed-off-by: Wei Ding <wei.ding@jd.com>

### CODE REVIEW

**Comment by chira001** [comment]
> @chira001 did the CFS project present to the CNCF Storage SIG? If so, what was the feedback?

@caniszczyk - yes - they presented and we are happy to move forward as a sandbox project.   I've just sent an email to the TOC mailing list with the collated info and a recording of the presentation.

**Comment by Vivian7755** [comment]
We have finished the presentation on last TOC weekly meeting, so what's the next step?

**Comment by Vivian7755** [comment]
ChubaoFS was presented at last TOC weekly meeting.  What's the next step?

**Comment by caniszczyk** [comment]
@monadic and @xiang90 can you confirm you are sponsoring this for the sandbox?

**Comment by monadic** [comment]
Correct - sandbox

**Comment by xiang90** [comment]
confirm.

**Pull request merged**
