### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by gochist**
Translated the definition in Korean.

### CODE REVIEW

**Comment by dankohn** [comment]
Thank you! We'll have some of our Korean partners review and then approve shortly.

**Comment by gochist** [comment]
@dankohn Hello! Can I get an update on this? If the partners are not available, I think @kubernetes/sig-docs-ko-owners can help with this.

**Comment by dankohn** [comment]
Apologies for the delay. Yes, could you please ask one or two other native Korean speakers from @kubernetes/sig-docs-ko-owners (and preferably not from your company) to do a review and then I'll merge.

**Comment by gochist** [comment]
@ianychoi Thank you! I have addressed your comments.

**Pull request merged**
