### PR TITLE
Add karmada incubation proposal

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
Karmada has been a CNCF sanbox projrect since Sep. 2021. The project and community keep growing over the last year.
We would like Karmada to be considered for incubation.

Thanks!

Signed-off-by: Kevin Wang <kevinwzf0126@gmail.com>

### CODE REVIEW

**Comment by nikhita** [comment]
Hi folks! I will be the TOC sponsor for karmada's incubation.

**Comment by kevin-wangzefeng** [comment]
FYI. The Due Diligence doc is available at: https://docs.google.com/document/d/1dm9mMANZ13UGTiNbW8DaDvrmuaAAJhHIoJmisQ6lUuI/edit#heading=h.17q6bz2003df

**Comment by RainbowMango** [comment]
@amye Is there anything we need to do with this PR?

And what's the next to get through the process?

**Pull request merged**
