### PR TITLE
Telepresence-2021-Annual Review

### PR DESCRIPTION
**Pull request by efunk**

### CODE REVIEW

**Comment by AaronFriel** [comment]
I would like to request additional information on:

1. Whether this statement in the [Telepresence FAQ](https://www.telepresence.io/docs/latest/faqs/) is accurate that it is not currently open source:

   >  Is Telepresence open source?
   > 
   > Telepresence will be open source soon, in the meantime it is free to download. We prioritized releasing the binary as soon as possible for community feedback, but are actively working on the open sourcing logistics.

   It appears the repository for the CLI has been updated with v2, but it would be helpful to clarify. It isn't clear where the [Agent Image](https://github.com/telepresenceio/telepresence/blob/8abb3d80b187da58df7ade9f31f3cb20c5fec4aa/pkg/client/envconfig.go#L23) is built, it appears to have a [Docker Hub entry](https://hub.docker.com/layers/datawire/ambassador-telepresence-agent/1.9.0/images/sha256-d153b9296e36d3c4938d5a3498bc4540d419c8d5500b1bb2921dbc289556835d?context=explore) but no source code is available. It looks like [the telepresence CLI](https://github.com/telepresenceio/telepresence/blob/8abb3d80b187da58df7ade9f31f3cb20c5fec4aa/pkg/client/cli/extensions/grpc.go#L33) requires obtaining an image from Ambassador Cloud.
   
   Where is the agent image and source code, and will they be provided as part of the `telepresenceio` GitHub organization?

2. Whether Ambassador Cloud's server, deeply integrated, into the Telepresence CLI, will be open sourced as well.
  
   The plugin architecture notwithstanding, much of the [Telepresence documentation](https://www.telepresence.io/docs/latest/tutorial/) begins with `telepresence login`, which requires creating an account with Ambassador Cloud.
   
   Features of Telepresence then require [license checks](https://github.com/telepresenceio/telepresence/blob/release/v2/pkg/client/connector/userd_auth/license.go) and [phone home](https://github.com/telepresenceio/telepresence/blob/23b9a2d8e0ea346250557d6be57b11df59c6a796/pkg/client/connector/command.go#L208) by [default](https://github.com/telepresenceio/telepresence/blob/release/v2/cmd/traffic/cmd/manager/service.go#L89).
   
   As mentioned above, Ambassador Cloud is currently a core part of the installation process. Blocking network requests to Ambassador Cloud results in errors using the CLI. If I locally block the datawire.io, auth.datawire.io, and getambassador.io domains, even with `cloud.skipLogin: true` in the config file:
   
   ```shell
   $ telepresence connect
   Launching Telepresence Daemon v2.3.4 (api v3)
   Telepresence Daemon quitting...done
   telepresence: error: connector.Connect: the traffic manager gRPC API timed out.  The current timeout 15s can be configured as "timeouts.trafficManagerAPI" in "/home/[...]/.config/telepresence/config.yml"
   ```
   
3. Whether the project is committed to the vendor neutral requirements for graduation, and how they will commit to ensuring that a competitor to Ambassador Cloud would be able to integrate into the Teleport CLI and cluster.

4. Whether documentation could updated to support vendor neutrality by clearly delineating the core features of the project and the value-add features provided by Ambassador Cloud.

5. Whether Telepresence will be trademarked and the mark(s) will be transferred to the Linux Foundation. (I could not find a trademark application at the present time.)

**Comment by efunk** [comment]
Responses included below.

> I would like to request additional information on:
> 
> 1. Whether this statement in the [Telepresence FAQ](https://www.telepresence.io/docs/latest/faqs/) is accurate that it is not currently open source:
>    > Is Telepresence open source?
>    > Telepresence will be open source soon, in the meantime it is free to download. We prioritized releasing the binary as soon as possible for community feedback, but are actively working on the open sourcing logistics.
>    
**Thanks for pointing this out; all code has been open source for quite some time and we will update the FAQ.**


>    
>    It appears the repository for the CLI has been updated with v2, but it would be helpful to clarify. It isn't clear where the [Agent Image](https://github.com/telepresenceio/telepresence/blob/8abb3d80b187da58df7ade9f31f3cb20c5fec4aa/pkg/client/envconfig.go#L23) is built, it appears to have a [Docker Hub entry](https://hub.docker.com/layers/datawire/ambassador-telepresence-agent/1.9.0/images/sha256-d153b9296e36d3c4938d5a3498bc4540d419c8d5500b1bb2921dbc289556835d?context=explore) but no source code is available. It looks like [the telepresence CLI](https://github.com/telepresenceio/telepresence/blob/8abb3d80b187da58df7ade9f31f3cb20c5fec4aa/pkg/client/cli/extensions/grpc.go#L33) requires obtaining an image from Ambassador Cloud.
>    Where is the agent image and source code, and will they be provided as part of the `telepresenceio` GitHub organization?

**The agent code is available in the Telepresence repository; see https://github.com/telepresenceio/telepresence/tree/release/v2/cmd/traffic/cmd/agent.** 


> 2. Whether Ambassador Cloud's server, deeply integrated into the Telepresence CLI, will be open sourced as well.

**The Telepresence CLI works without Ambassador Cloud, and all the source code for this is available. Ambassador Cloud utilizes a plug-in interface to the CLI to ensure that it can operate independently. We will not be open sourcing Ambassador Cloud.**

>    The plugin architecture notwithstanding, much of the [Telepresence documentation](https://www.telepresence.io/docs/latest/tutorial/) begins with `telepresence login`, which requires creating an account with Ambassador Cloud.
>    Features of Telepresence then require [license checks](https://github.com/telepresenceio/telepresence/blob/release/v2/pkg/client/connector/userd_auth/license.go) and [phone home](https://github.com/telepresenceio/telepresence/blob/23b9a2d8e0ea346250557d6be57b11df59c6a796/pkg/client/connector/command.go#L208) by [default](https://github.com/telepresenceio/telepresence/blob/release/v2/cmd/traffic/cmd/manager/service.go#L89).
>    As mentioned above, Ambassador Cloud is currently a core part of the installation process. Blocking network requests to Ambassador Cloud results in errors using the CLI. If I locally block the datawire.io, auth.datawire.io, and getambassador.io domains, even with `cloud.skipLogin: true` in the config file:
>    ```shell
>    $ telepresence connect
>    Launching Telepresence Daemon v2.3.4 (api v3)
>    Telepresence Daemon quitting...done
>    telepresence: error: connector.Connect: the traffic manager gRPC API timed out.  The current timeout 15s can be configured as "timeouts.trafficManagerAPI" in "/home/[...]/.config/telepresence/config.yml"
>    ```
**We test this exact case in our internal tests because we want to ensure that the open source CLI works just fine without the Cloud and those tests are continuing to prove that it does.**

**You’ve encountered an issue with your configuration that is not related to Cloud. When connecting to the traffic manager in your cluster for the first time, the cluster needs to retrieve the image for the traffic manager from our public Docker repository, which can take some time. As noted in the error message, you can increase your timeout to address this issue.**


> 3. Whether the project is committed to the vendor neutral requirements for graduation, and how they will commit to ensuring that a competitor to Ambassador Cloud would be able to integrate into the Teleport CLI and cluster.

**We’re major supporters of the CNCF and fully support its core principles. As such, we are 100% supportive of vendor neutrality.  As noted in our update, our goal for incubation and beyond is to have committer maintainers from other organizations. Should a maintainer wish to use the same plug in architecture, we would have no issue with it.**

> 4. Whether documentation would be updated to support vendor neutrality by clearly describing in the documentation and Telepresence site which features are the core free and open source features of the project and which are value-adds provided by the "plugin" to Ambassador Cloud.

**While we strive to be vendor neutral, we are not perfect. As you may have noticed, an extensive amount of development is occurring in the Telepresence repository. As such, documentation is one of the areas where we could use more assistance. Any pull requests for issues such as these are welcome!**

> 5. Whether Telepresence will be trademarked and the mark(s) will be transferred to the Linux Foundation. (I could not find a trademark application at the present time.)

**As this is a CNCF project, we defer to the CNCF/LF on trademarks.**

**Comment by AaronFriel** [comment]
@efunk thank you for responding! I'm happy to know that Telepresence is committed to be vendor neutral.

I think it would be very helpful if the documentation was clearer on what features required a license or will cause a machine to "phone home". It does not appear to be possible to deploy Telepresence in an "airgapped" cluster or one with strict network policies as the CLI and/or installed service (I'm not equipped to debug) fails with the error above.

Will there be documentation available on how to use the CLI and/or service such that they do not have a dependency on Ambassador Cloud?

**Comment by efunk** [comment]
**@AaronFriel please see our responses below:**

> @efunk thank you for responding! I'm happy to know that Telepresence is committed to be vendor neutral.
> 
> I think it would be very helpful if the documentation was clearer on what features required a license or will cause a machine to "phone home". It does not appear to be possible to deploy Telepresence in an "airgapped" cluster or one with strict network policies or in a VPC with strict firewall rules as the CLI and/or installed service (I'm not equipped to debug) fails with the error above.
> 
**Our testing has validated that Telepresence does work in an "airgapped" cluster and we are adding additional automated tests to ensure that Telepresence continues to work in that environment. If you are continuing to see issues with the latest release, please open an issue, or, better yet, a pull request, with the details of the environment and log files so that we can provide a resolution in a future release.**

> Will there be documentation available on how to use the CLI and/or service such that they do not have a dependency on Ambassador Cloud?

**Yes. Telepresence functionality does not inherently depend on Ambassador Cloud, and the documentation today, to the best of our knowledge, reflects this. We aren't perfect though. If you know of a great documentation lead (see our careers page:  https://jobs.lever.co/AmbassadorLabs/a920a456-4235-44ce-b7bc-47a2b84bc956 ) and/or are able to test and work on PRs, we'd be eternally grateful.**

**Comment by clebio** [comment]
Hi @efunk, thanks for responding to @AaronFriel 's questions. I subscribed to this PR since I've also been following the Ambassador Telepresence project for a while, but share some of Aaron's concerns.

Help me understand this build workflow for the Dockerhub agent container which Aaron referenced. I see the make target to "Build/tag the manager/agent container image", here:
https://github.com/telepresenceio/telepresence/blob/release/v2/build-aux/main.mk#L81

And that that uses `ko publish`. However, the image layers for `datawire/ambassador-telepresence-agent` on Dockerhub point to a path that doesn't appear in that repo:
https://hub.docker.com/layers/datawire/ambassador-telepresence-agent/1.10.0/images/sha256-f6e7816d5774fd845de0746b7fd34bdb8c14edf85b67f227ee4b23c37f7bbbbf?context=explore

That is, `ko publish ko://github.com/datawire/telepresence2/proprietary/cmd/app-sidecar` presumably comes from a `proprietary/cmd/app-sidecar` path, which is not present under https://github.com/telepresenceio/telepresence/tree/release/v2/cmd

That doesn't match with the link which you provided,
> The agent code is available in the Telepresence repository; see https://github.com/telepresenceio/telepresence/tree/release/v2/cmd/traffic/cmd/agent.

So all we really have to work with is a compiled go binary, based on a proprietary source path. Maybe I'm misreading the make targets, though?

**Comment by thallgren** [comment]
Hi @clebio . The docker image is built in three steps:

1. The [line that you refer to in main.mk](https://github.com/telepresenceio/telepresence/blob/release/v2/build-aux/main.mk#L81) makes `ko` build the image locally directly from the go source under `./cmd/traffic`
2. The  next line tags the image. The latest released tag is `docker.io/datawire/tel2-v2.4.0`.
3. The `push-image` target on line 85 pushes the image to the docker repository under the given tag and consequently, the image ends up here: https://hub.docker.com/r/datawire/tel2/tags
 
You are correct that images under `datawire/ambassador-telepresence-agent` are proprietary. They are not used unless the user is logged in to Ambassador Cloud. The source for those images is not publically available.

**Comment by efunk** [comment]
Hi @clebio. I think it would be better to take this technical discussion away from the PR and into a more interactive setting. 

I would like to invite you to our next Meet the Maintainers session on Wednesday, August 18 at 10:00am ET. There, myself and the developers of Telepresence will present on what we have recently released and be available for some Q&A with the user community.

Details for attending the session can be found here: https://www.getambassador.io/about-us/events/meet-the-maintainers-sessions/telepresence/081821/

I hope to see you there.

**Pull request merged**
