### PR TITLE
Propose PARSEC for inclusion to CNCF Sandbox

### PR DESCRIPTION
**Pull request by paulhowardarm**
This PR introduces the proposal to include PARSEC in the sandbox.

Signed-off-by: Paul Howard <paul.howard@arm.com>

### CODE REVIEW

**Comment by alena1108** [comment]
This project falls under SIG Security 

cc @amye

**Comment by amye** [comment]
Thank you! I will kick off an issue in SIG-Security for assessment.

**Comment by hannibalhuang** [comment]
really glad to see PARSEC apply for CNCF Sandbox !

**Comment by rficcaglia** [comment]
created assessment [slack channel](https://cloud-native.slack.com/archives/C0154QH5Z43)

**Comment by amye** [comment]
Parsec was accepted into the sandbox:
https://lists.cncf.io/g/cncf-toc/message/4853

project onboarding will happen here https://github.com/cncf/toc/issues/469

**Pull request merged**
