### PR TITLE
Kuma 2022 Annual Review

### PR DESCRIPTION
**Pull request by lahabana**
This is based off of the [Sandbox Annual Review](https://github.com/cncf/toc/blob/master/process/sandbox-annual-review.md) process. 
- [x] Is your PR called: [Project name] [year] Annual Review?
- [x] Did you include a file for <year>-<project name>-annual.md?
- [x] Did you include a link to your project’s devstats page?
- [x] Did you include a link to your MAINTAINERS file?
- [x] What do you know about adoption? Is there an existing ADOPTERS file?
- [x] Did you include any previous goals?
- [x] Are your current goals listed?
- [x] Did you include requests from the CNCF?
- [x] Do you want to start the process for incubation? (This is a separate process)  Yes very soon

### CODE REVIEW

**Comment by lahabana** [comment]
Hi @TheFoxAtWork are we missing anything to get this reviewed?

**Comment by TheFoxAtWork** [comment]
@lahabana nope, the onus is on the TOC.  We implemented a pilot effort with the TAGs which we just got feedback on and will be shifting gears over the next few months.  Any Annual Review not currently with a TAG will be completed by the TOC (with support from CNCF) by end of year. Apologies for the delay.

**Review by linsun — APPROVED** [review]
LGTM

Congrats on the adaptions!

Main concern for next stage (incubation) is the maintainer vendor diversity.

**Comment by TheFoxAtWork** [comment]
@mauilion @rochaporto As TOC Liaisons for this TAG, would you review/approve/merge from the TAG's comment/recommendation?

**Comment by amye** [comment]
Marking this as complete, annual reviews are no longer a requirement for sandbox. 
We'll be rolling out more efficient ways to show project health and metrics in 2024.

**Pull request merged**
