### PR TITLE
add brigade sandbox proposal

### PR DESCRIPTION
**Pull request by michelleN**

### CODE REVIEW

**Comment by caniszczyk** [comment]
Hey @brendandburns and @quinton-hoole can you confirm you sponsor this?

**Comment by quinton-hoole-2** [comment]
Ack

**Comment by brendandburns** [comment]
Ack

**Comment by caniszczyk** [comment]
Brigade is in as a sandbox project, we will work with the team to transfer ownership of items and get them setup on the new github org

**Pull request merged**
