### PR TITLE
k8gb-2022-Annual Review

### PR DESCRIPTION
**Pull request by jkremser**
Add `reviews/2022-k8gb-annual.md`

Signed-off-by: Jirka Kremser <jiri.kremser@gmail.com>
Signed-off-by: Timofey Ilinykh <ilinytim@gmail.com>
Signed-off-by: Yury Tsarev <yury@upbound.io>

### CODE REVIEW

**Comment by dims** [comment]
Assigning @kgamanji as the TOC shepherd for the TOC meeting on 6/21

**Comment by kgamanji** [comment]
@jkremser the TOCs have discussed k8gb project at the annual review meeting this week. Overall, we are happy with the content of the annual review, however here are the **recommendations** that hopefully will drive the growth of the project:
 - The contributors base and maintainership need more diversification (5 out of 6 contributors are from the same organization)
 - Activity is present (issues/PRs) however not at the same scale. Getting more contributors and an end user base might be helpful to increase the project activity
 -  Increase your visibility within the landscape. Integration with Operator Hub and Artifactory Hub is a great first step - keep doing it! Collaboration and integration with other cloud providers (Azure, GCP) might help with this point too
 - Could not find a roadmap. If present can you please link it? If not present, highly recommend creating one to increase transparency into where the project is moving and helping contributors get involved
 - Celebrate your success! List your adopters and their use case to create trust about k8gb running in production
 
 Overall, a great project with a well-defined value, however, if the goal is incubation, then we recommend taking action on the above recommendations.
 
For more details slides are here: https://docs.google.com/presentation/d/1ARxZNb5orglbugP8CWn7ssqH-R_xidP6UMCaxZnN0Yo and the recording is available here: https://www.youtube.com/watch?v=VpkYtxzd13E&t=1204s&ab_channel=CNCF%5BCloudNativeComputingFoundation%5D







[Katie Gamanji](https://app.slack.com/team/UEEV0BCUR)
  [2 days ago](https://cloud-native.slack.com/archives/G01MNU51LFM/p1655818829889659?thread_ts=1655818700.079749&cid=G01MNU51LFM)
Would be great to see a diverse contributor and adopter base. k8bg visibility increased since joining sandbox, but need to put a bit more effort in their growth if they want to reach incubation

**Comment by kgamanji** [comment]
@jkremser the TOCs have discussed k8gb project at the annual review meeting this week. Overall, we are happy with the content of the annual review, however here are the **recommendations** that hopefully will drive the growth of the project:

- The contributors base and maintainership need more diversification (5 out of 6 contributors are from the same organization)
- Activity is present (issues/PRs) however not at the same scale. Getting more contributors and an end user base might be helpful to increase the project activity
- Increase your visibility within the landscape. Integration with Operator Hub and Artifactory Hub is a great first step - keep doing it! Collaboration and integration with other cloud providers (Azure, GCP) might help with this point too
- Could not find a roadmap. If present can you please link it? If not present, highly recommend creating one to increase transparency into where the project is moving and helping contributors get involved
- Celebrate your success! List your adopters and their use case to create trust about k8gb running in production

Overall, a great project with a well-defined value, however, if the goal is incubation, then we recommend taking action on the above recommendations.

For more details slides are here: https://docs.google.com/presentation/d/1ARxZNb5orglbugP8CWn7ssqH-R_xidP6UMCaxZnN0Yo and the recording is available here: https://www.youtube.com/watch?v=VpkYtxzd13E&t=1204s&ab_channel=CNCF%5BCloudNativeComputingFoundation%5D

**Comment by ytsarev** [comment]
Hi @kgamanji thank you so much for this summary, the recommendations are extremely valuable.

Regarding the roadmap, we are using a lightweight GitHub Issue-based prioritization process as of now, see  https://github.com/k8gb-io/k8gb/milestones .

I think we would be happy to use something more visible, could you suggest good reference roadmap examples from other CNCF projects?

**Pull request merged**
