### PR TITLE
Add proposal for Flux moving to incubation

### PR DESCRIPTION
**Pull request by squaremo**
This introduces a proposal to graduate Flux from sandbox into incubation.

In summary, it:

 * Fills in background and Flux v2 roadmap
 * Mentions Flagger (prospectively) joining
 * Links to governance, security and contribution codes
 * Addresses each incubation requirement

### CODE REVIEW

**Comment by caniszczyk** [comment]
Any @cncf/toc members interested in sponsoring + due diligence work?

**Comment by michelleN** [comment]
I'm supportive and I'm happy to sponsor. @AloisReitbauer - could we get SIG App Delivery to review and provide a recommendation for this project? Moving to the SIG review column.

**Comment by michelleN** [comment]
+1

**Comment by michelleN** [comment]
Took a read through the Flux DD document [here](https://docs.google.com/document/d/1Z6yPN9-bWeVGpMrBxXJ3NBTBYZowJ3R93wKHEVmBJ1A/edit#) and left some comments. I believe there are still sections that need to be filled in. I'd be happy to take another look when it is complete.

**Comment by resouer** [comment]
I will take as the primary contact role for this process on SIG App Delivery side and help to make the DD doc complete with more detailed information to TOC.

**Comment by dzolotusky** [comment]
@michelleN - Since I haven't sponsored any projects so far, could I tag along somehow to see what you do throughout this process and co-sponsor or shadow you or something?

**Comment by dzolotusky** [comment]
> Took a read through the Flux DD document [here](https://docs.google.com/document/d/1Z6yPN9-bWeVGpMrBxXJ3NBTBYZowJ3R93wKHEVmBJ1A/edit#) and left some comments. I believe there are still sections that need to be filled in. I'd be happy to take another look when it is complete.

I don't have access to this doc. Could someone give me access to read through it?

**Comment by dholbach** [comment]
@AloisReitbauer can you change the document's permissions? I unfortunately can't.

**Comment by dholbach** [comment]
As quite a few are watching this issue, here is a brief update:

- The DD doc is visible now and should generally be in a good shape.
- @michelleN interviewed some of the Flux production users in the meantime, @resouer provided input and questions as well.

Thanks for everybody's support so far! <3

**Comment by amye** [comment]
Public comment period open: https://lists.cncf.io/g/cncf-toc/message/5644

**Comment by amye** [comment]
Vote is open! https://lists.cncf.io/g/cncf-toc/message/5680

**Comment by caniszczyk** [comment]
incubation it is!

9/11
Michelle Noorali: https://lists.cncf.io/g/cncf-toc/message/5682
Sheng Liang: https://lists.cncf.io/g/cncf-toc/message/5684
Justin Cormack: https://lists.cncf.io/g/cncf-toc/message/5686
Alena Prokharchyk: https://lists.cncf.io/g/cncf-toc/message/5697
Liz Rice: https://lists.cncf.io/g/cncf-toc/message/5700
Cornelia Davis: https://lists.cncf.io/g/cncf-toc/message/5699
Dave Zolotusky: https://lists.cncf.io/g/cncf-toc/message/5705
Lei Zhang: https://lists.cncf.io/g/cncf-toc/message/5720
Ricardo Rocha: https://lists.cncf.io/g/cncf-toc/message/5732

**Pull request merged**
