### PR TITLE
TOC principles

### PR DESCRIPTION
**Pull request by dankohn**
I took the TOC Principles [document](https://docs.google.com/document/d/1Yl3IPpZnEWJRaXSBsTQ22ymQF57N5x_nHVHvmJdAj9Y/edit) created by several TOC members and:

1. Converted it to markdown.
2. Left out the notes and comments on the budget.

The notes and comments are important (and remain in the original Google Doc), but will hopefully be addressed by the CNCF ServiceDesk and Service Dashboard that we'll be announcing in the next couple weeks.

For now, the TOC and I would appreciate your comments on the Principles themselves. If you don't think they adequately describe the way the TOC operates (and/or how it should operate), then please comment on the pull request.

Once comments are addressed, the goal is for the TOC to vote that this document represents the TOC Principles, and to have the CNCF governing board vote to endorse the Principles as well.

Rendered version
https://github.com/cncf/toc/blob/toc-principles/principles.md

Pull request (comments welcome)
https://github.com/cncf/toc/pull/47/files

TOC Principles (i.e., the original document)
https://docs.google.com/document/d/1Yl3IPpZnEWJRaXSBsTQ22ymQF57N5x_nHVHvmJdAj9Y/edit

Thanks.

### CODE REVIEW

**Comment by caniszczyk** [comment]
RFC @cncf/toc

**Comment by bgrant0607** [comment]
Thanks. I believe this accurately transcribes the doc, from what I can remember, and seems like a fine basis for us to iterate and elaborate on.

**Comment by hjacobs** [comment]
Looks great! :smile:

**Comment by liljenstolpe** [comment]
I agree that it is a good transcription, and agree with document.  +1

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
@countspongebob 

"No kingmakers" is really a distinct point. The section on self-governance discusses community ownership and formal processes by which contributors can become committers.

The language in the graduation criteria around "healthy number of contributors" and committers from multiple organizations was debated in the original doc:

https://docs.google.com/document/d/1l6e-hW7C3S6xJjGn47hUKKxeFBxiamAK7kn5efSryxY/edit#heading=h.w36a7s79wajn

When we vet projects, even at the inception level, one criterion we use is whether we believe the project will eventually meet the graduation criteria.

**Comment by countspongebob** [comment]
I concede that conflating kingmaking and healthy governance checks may be confusing and focus on healthy governance. 

The role terms must be better defined, and I will open comment against that doc. I would still like to see a stronger position taken on cross-org project governance taken directly by the TOC, but will push the specifics into a different comment stream where my concerns remain.

I think the process will be easier to manage if we can approve this version and make edits by pull request after that - I could suggest stronger language to this version but I would advocate for establishing an acceptable baseline, which I believe this doc represents.

We continue to run the risk of single-org projects using the CNCF for short-term marketing gain without gaining their commitment to multi-org operation. We leave this check very late in the process, and many projects will get all the (kingmaking-ish) benefits without the corresponding commitments.

**Comment by skamille** [comment]
Lgtm

**Comment by leecalcote** [comment]
Given the number of existing projects, I agree that we should consider the addition of some form of "interoperability with other CNCF projects" as criteria in the Graduation Stage - https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc

**Comment by rothgar** [comment]
I know I'm late on providing feedback for this doc, but is there any guidelines or rules about retiring projects from the CNCF? Do they live on forever or is there some vote that should happen when projects are seen as no longer relevant?

**Comment by dankohn** [comment]
Everyone I've spoken to in the TOC is very open to retiring projects that
they can no longer recommend. I even had some language in that regard in a
previous version of the graduation criteria:
https://www.cncf.io/projects/graduation-criteria/ although it was removed
as premature. Retiring a project simply requires a 2/3rds vote of the TOC,
like any other action.

However, since it hasn't happened yet, there are not widely-agreed
criteria, and so I think it makes sense that it's not (yet) in the TOC
principles.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by bgrant0607** [comment]
Created a backlog and added the retirement issue to it:
https://github.com/cncf/toc/projects/1#card-5540854

**Comment by bgrant0607** [comment]
@countspongebob @leecalcote I added interoperability to the backlog:
https://github.com/cncf/toc/projects/1#card-5540975

**Comment by rothgar** [comment]
Thanks. LGTM

**Comment by caniszczyk** [comment]
As an FYI, we now have enough votes from the @cncf/toc to approve this:
https://lists.cncf.io/pipermail/cncf-toc/2017-November/thread.html#1314

I'm going to leave this open another day to see if any remaining TOC members want to get their votes in.

**Comment by samlambert** [comment]
:+1:

**Comment by caniszczyk** [comment]
merging in, we have unanimous TOC approval!

+1 binding TOC votes from:

Alexis: https://lists.cncf.io/pipermail/cncf-toc/2017-November/001382.html
BrianG: https://lists.cncf.io/pipermail/cncf-toc/2017-November/001314.html
Solomon: https://lists.cncf.io/pipermail/cncf-toc/2017-November/001324.html
Jon: https://lists.cncf.io/pipermail/cncf-toc/2017-November/001353.html
Ken: https://lists.cncf.io/pipermail/cncf-toc/2017-November/001354.html
Ben: https://lists.cncf.io/pipermail/cncf-toc/2017-November/001355.html
Camille: https://lists.cncf.io/pipermail/cncf-toc/2017-November/001379.html
Bryan: https://lists.cncf.io/pipermail/cncf-toc/2017-November/001380.html
SamL: https://github.com/cncf/toc/pull/47#issuecomment-344150385

**Pull request merged**
