### PR TITLE
Added Proposal for advancing Thanos to the Incubation Stage 🎉

### PR DESCRIPTION
**Pull request by bwplotka**
:wave: 

During Thanos presentation at the [CNCF TOC meeting on 7/9/2019](https://docs.google.com/presentation/d/1jhzJlSAAJNNil1nIYp60eSMH3LPd6AwqHLt3vEAzMSg/edit#slide=id.g5cdf155fc3_0_4) we were suggested by TOC members to apply straight for [the Incubation Stage](https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc#incubating-stage).
We all agreed back then that we will join Sandbox first and after that perform Due Diligence required for the Incubation Stage. 
 
This proposal aims to address the Diligence requirements and as the Thanos team, we believe we are ready to be considered joining Incubation Stage.

We are aware that TOC members are busy nowadays, but we are looking forward to potential next steps regarding this application :hugs: 

cc @caniszczyk @amye

@thanos-io/thanos-maintainers
@thanos-io/thanos-triage

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by brendandburns** [comment]
I think this should first go through a detailed review with SIG-Observability, right?

**Comment by bwplotka** [comment]
That's correct. I think we are close to starting the Observability SIG up, right? 

https://github.com/cncf/sig-observability/pull/1

**Comment by kgamanji** [comment]
I will conduct the DD for Thanos. Will reach out with more details once I have started  the DD

**Comment by povilasv** [comment]
@kgamanji Thank you! FYI this is the DD doc we reviewed during Sig Observability meeting  https://docs.google.com/document/d/1jJk5seSUcgwybT4nVGOzaRGrugc90uL3WCY0fUgQh1M/edit#

if you have any questions / suggestions let me know. I'm available as povilasv on CNCF slack. We also have `#thanos` for general/community questions.

**Comment by kgamanji** [comment]
I have now completed the DD for Thanos. Here are my key points:
- Thanos has a solid end-user base with multiple success stories 
- healthy contributor community, including a triage team
- good focus on interoperable components

One point I would like more details:
- currently there are plenty on initiatives to improve the projects, such as [proposals](https://github.com/brancz/thanos/tree/7ded45b6d6b1082f236fe08532935d398b31b3d5/docs/proposals) (tho not part of the master branch), [consolidation of Helm charts](https://docs.google.com/document/d/18GXxwOm9c2fDK20LV1Sekte0xvK4qXpIGwBcuw_ZYSA/edit#heading=h.bupciudrwmna), [OLAP](https://github.com/thanos-io/thanos/issues/2682) and [removal of Prometheus metrics](https://docs.google.com/document/d/1jJk5seSUcgwybT4nVGOzaRGrugc90uL3WCY0fUgQh1M/edit?disco=AAAAJvvDGwA). Is there a unified roadmap to showcase the priority items and features to focus on?


Overall, the project meets the incubation criteria and I am happy to move the project forward once I have more details on the above.

**Comment by povilasv** [comment]
We have roadmap https://github.com/thanos-io/thanos/projects/8#card-32246725, which has most of the major features.

For removal it has open issue: https://github.com/thanos-io/thanos/issues/1598
For Helm charts it's: https://github.com/thanos-io/thanos/issues/1820

We mostly use github issues for tracking feature requests and bugs / fixes.

**Comment by kgamanji** [comment]
Thank you for the details.

I will progress with opening the public comment period.

**Comment by caniszczyk** [comment]
https://lists.cncf.io/g/cncf-toc/message/5198

+1 binding
9/11
Brendan Burns: https://lists.cncf.io/g/cncf-toc/message/5076
Katie Gamanji: https://lists.cncf.io/g/cncf-toc/message/4992
Matt Klein: https://lists.cncf.io/g/cncf-toc/message/5001
Alena Prokharchyk: https://lists.cncf.io/g/cncf-toc/message/5013
Liz Rice: https://lists.cncf.io/g/cncf-toc/message/5075
Xiang Li: https://lists.cncf.io/g/cncf-toc/message/5139
Justin Cormack: https://lists.cncf.io/g/cncf-toc/message/5147
Sheng Liang: https://lists.cncf.io/g/cncf-toc/message/5164
Michelle Noorali: https://lists.cncf.io/g/cncf-toc/message/5170

**Pull request merged**
