### PR TITLE
Keycloak Submission for Incubation

### PR DESCRIPTION
**Pull request by bdaw**
Due to changes to Sandbox project definition Keycloak would like to pursue Incubation status instead. 

Previous Sandbox PR: https://github.com/cncf/toc/pull/405
Previous Sandbox Issue: https://github.com/cncf/toc/issues/406

Other useful links:

Keycloak Pitch (Short) Video [1m 42s]: https://www.youtube.com/watch?v=GZTN_VXjoQw

Keycloak Introduction Video [32min 11s] https://www.youtube.com/watch?v=duawSV69LDI

Link to GitHub project: https://github.com/keycloak

Getting Started / Trying out: https://www.keycloak.org/getting-started

CNCF SIG Security assesment request:
https://github.com/cncf/sig-security/issues/372

CNCF SIG Security Self Assesment document with great level of details about the project:
https://docs.google.com/document/d/14IIGliP3BWjdS-0wfOk3l_1AU8kyoSiLUzpPImsz4R0/edit#

Link to initial 2018 Presentation: (Oct 2018 TOC presentation - slide 26)
https://docs.google.com/presentation/d/1Xt1xNSN8_pGuDLl5H8xEYToFss7VoIm7GBG0e_HrsLc/mobilepresent?slide=id.g3f805096e4_212_0

### CODE REVIEW

**Comment by kfox1111** [comment]
Any movement on this?

**Comment by amye** [comment]
@bdaw  - is this still active? I'm doing an end of year cleanup, and will be closing inactive PRs by the end of the week, 12/17.
It doesn't mean that you can't reapply!

**Comment by bdaw** [comment]
Keycloak remains interested in pursuing the submission. My understanding is that project has completed everything which has been required according to the process and this issue has been awaiting for DD from TOC side as a next step. 

Worth highliting is that in the meantime Keycloak made progress in all areas which has been raised as concerns from TOC side in the past - even thought not being agaist any formal requirements

- There are two new (non Red Hat) maintainers: 
https://www.keycloak.org/2021/09/thomas.adoc 
https://www.keycloak.org/2021/10/takashi.adoc

- Project is moving to Github Issues and abandoning JIRA instance hosted by Red Hat:
https://groups.google.com/g/keycloak-dev/c/93aMF6uCuBs/m/3DuNkNQeBQAJ

- Project accelerated efforts around rearchitecture and new runtime:
https://www.keycloak.org/2021/10/keycloak-x-update

**Comment by rochaporto** [comment]
Hi @bdaw . Quick check here, is there still interest in moving forward with this?

**Comment by abstractj** [comment]
Hi @rochaporto, the answer is yes. Currently, we have been actively working on the due diligence document.

**Comment by rochaporto** [comment]
Thanks @abstractj . I'll be happy to help out here.

**Comment by rochaporto** [comment]
The DD document looks ready for public comment. There are two minor suggestions could you have a quick look? I'll send the announcement right after.

**Comment by xgp** [comment]
Hi @rochaporto Is the public comment period over for this? Do you have an update on the status of Keycloak's incubation application?

**Pull request merged**
