### PR TITLE
Add Backstage as CNCF Sandbox project

### PR DESCRIPTION
**Pull request by stefanalund**
This PR contains a proposal to add **Backstage** to the CNCF as a Sandbox project.

We have time allocated with the [App Delivery SIG](https://github.com/cncf/sig-app-delivery) to present the project and proposal and will follow up on this PR when that is complete.

**Description:** [Backstage](https://backstage.io/) is an open platform for building developer portals. It’s based on the developer portal we’ve been using internally at Spotify for over four years. Backstage can be as simple as a services catalog or as powerful as the UX layer for your entire tech infrastructure.

### CODE REVIEW

**Comment by amye** [comment]
Lovely! Please add yourself through the [Sandbox Application Form](https://docs.google.com/forms/u/2/d/1bJhG1MuM981uQXcnBMv4Mj9yfV5_q5Kwk3qhBCLa_5A/edit).

**Comment by stefanalund** [comment]
@amye done ✔️ 🙏🏼

**Comment by dtuite** [comment]
I spent a few years working on developer portals and talking to other infra product managers who tried to build something inside their own company. Nothing comes close to what Spotify have achieved with their internal developer portal. 

Backstage would be a fantastic and complementary addition to the suite of CNCF tools.

**Comment by mijailr** [comment]
+1000 including backstage as a CNCF project is valuable for the project future. 🎉

**Comment by monadic** [comment]
big +1 for this 

we tried backstage and liked it!  https://www.weave.works/blog/implementing-a-gitops-ui-with-spotify-s-backstage

**Comment by stefanalund** [comment]
Update: since submitting Backstage for Sandbox, quite a few companies have added themselves to [ADOPTERS](https://github.com/spotify/backstage/blob/master/ADOPTERS.md).

**Pull request merged**
