### PR TITLE
KubeArmor 2022 Annual Review

### PR DESCRIPTION
**Pull request by nyrahul**
Annual review as per [CNCF TOC guidelines](https://github.com/cncf/toc/blob/main/process/sandbox-annual-review.md#how-to-file-your-annual-review).

Fixes: kubearmor/kubearmor#1248

### CODE REVIEW

**Comment by PushkarJ** [comment]
@nyrahul I know it's been a while since this PR was created and we have not gotten back to you. 

Are you still looking for a review / feedback on this ? If yes, are there any changes you would like to make to the PR considering it was created a few months back or is it ready for review as is?

**Comment by nyrahul** [comment]
Hey @PushkarJ , I will make the updates today to the PR. Things have greatly improved in the last six months for KubeArmor community engagement and the updated PR will reflect that. Thanks

**Comment by PushkarJ** [comment]
Thank you Rahul for the updates. 

@toc Please remove label for tag-security as we were unable to complete the review of the PR by Jan 1 deadline.

**Comment by amye** [comment]
Marking this as complete, annual reviews are no longer a requirement for sandbox. 
We'll be rolling out more efficient ways to show project health and metrics in 2024.

**Pull request merged**
