### PR TITLE
added kubeinvaders

### PR DESCRIPTION
**Pull request by lucky-sideburn**
Hi!
I would like to propose my latest project: Kubeinvaders.

It is a gamified chaos engineering tool for Kubernetes. It is like Space Invaders but the aliens are PODs.

### CODE REVIEW

**Comment by lucky-sideburn** [comment]
Hi! Can I ask if the project can be approve for sandbox?

**Comment by lucperkins** [comment]
@lucky-sideburn I would strongly recommend providing more information in your proposal. You can see other project proposals [here](https://github.com/cncf/toc/tree/master/proposals).

**Comment by lucky-sideburn** [comment]
Hi @lucperkins thank you for your suggestion! I will add to my proposal all required details

**Comment by lucky-sideburn** [comment]
Hi @lucperkins I integrated some contents in order to explain better my proposal.

https://github.com/cncf/toc/pull/316/files#diff-5a410f312e0331f66b2a68386baa5401

**Comment by lucky-sideburn** [comment]
> @lucky-sideburn I would strongly recommend providing more information in your proposal. You can see other project proposals [here](https://github.com/cncf/toc/tree/master/proposals). It's not clear for whom the project is intended or whom it would potentially benefit.

Added some info about the project! https://github.com/cncf/toc/pull/316/files#diff-5a410f312e0331f66b2a68386baa5401

**Pull request closed without merging**
