### PR TITLE
Add Artifact Hub incubation proposal

### PR DESCRIPTION
**Pull request by tegioz**
Hi! 👋

This is a proposal to consider Artifact Hub as a CNCF incubation project.

Please let us know if there is anything missing and we'll gladly provide more details.

Thanks!

Signed-off-by: Sergio Castaño Arteaga <tegioz@icloud.com>

### CODE REVIEW

**Comment by scottrigby** [comment]
+1 nb. I've seen incredible success with the artifact of project since its inception. The maintainers are dedicated, focused, and I believe have fulfilled Dan's vision for AH before he passed, and even more than that. Also, with the expanding relevance of OCI artifacts as storage for all of these project configuration formats, Artifact Hub also seems well positioned to serve a much bigger role for the cloud native community. Great work team 💯

**Comment by rochaporto** [comment]
As a counter-argument i would say artifacthub is part of the infrastructure and the cloud native stack for many end users, even if not deployed locally. Using CERN as an example we rely on artifacthub for a very large number of replication rules for our local Harbor instance, using the central artifacthub as the main source to discover and replicate upstream helm charts and container images.

It's not the typical project where people maintain their own instances, which makes it hard to match the usual criteria. But it's part of our stack and an important piece of our production infrastructure. The description in this submission focuses mostly on the number of organizations publishing to artifacthub, but there are many more relying on it as consumers and that should be taken into account.

**Comment by tegioz** [comment]
Hi @dmueller2001 👋

> Is there a list (if any) of any other deployments of artifacthub's codebase by any other foundations or technology initiatives or enterprises available?

Unfortunately we don't have a list yet, as it hasn't been easy to have them list themselves as adopters 😅 But every now and then, users running their own AH instance in their organizations stop by the Slack channel to ask some questions, or request new features.

Although it's not a very scientific way of measuring adoption, the [Artifact Hub Helm chart on artifacthub.io](https://artifacthub.io/packages/helm/artifact-hub/artifact-hub#views) receives quite a few visits every day (screenshot attached below). And that chart is only relevant to deploy your own AH instance. In addition to that, as of today, 17 users are subscribed to receive notifications for new releases for that chart, and there are 5 webhooks attached to receive notifications as well. As a reference to compare, the [Consul Helm chart](https://artifacthub.io/packages/helm/hashicorp/consul#views) shows similar numbers both in terms of visits and subscriptions.

ah-chart-views

> it is not Cloud Native technology any more than the CNCF's website/portal itself

Maybe we are not doing a good job describing what it can do for organizations, and that could help 🙂

*"Artifact Hub provides a centralized Cloud Native artifacts catalog for your organization. It is able to index and process 20 different artifacts kinds (and growing!), including Helm charts and OLM operators, providing a unified interface to share, discover and easily inspect all sorts of Kubernetes packages available across the organization."*

We were hoping that a catalog for Cloud Native artifacts would be Cloud Native technology 😇 And we think it can bring a lot of value to organizations (unlike deploying their own copy of the CNCF's website), as many of the problems that artifacthub.io solves for users consuming the public content available, also need to be solved for private content in other organizations, specially large ones.

**Comment by dmueller2001** [comment]
Thanks for the feedback, doesn't change my -1 NB vote or opinion. Having worked with other hubs and packaging initiatives over the years,  a strong community of maintainers and contributors is key to their stability and maturity.  As an example,   https://github.com/pypi/warehouse/graphs/contributors has a long history of community engagement in the development of the infrastructure that supports PyPi.  

I concur with at @rochaporto's statement that many enterprises are using Artifacthub.io as the main source to discover and replicate upstream helm charts, container images,  There is a clear dependency on the hosted codebase as ArtifactHub.io as a resource that should be well maintained and managed infrastructure. 

There is little external or community resources working on the codebase at this time, and a large number of dependent consumers of the service. As such, I'd rather see this initiative considered critical infrastructure and have the CNCF/LF continue to fund and manage it as such.

**Comment by dzolotusky** [comment]
I want to be clear that I agree with most of these questions being the heart of the debate with Artifact Hub, and as its sponsor have gone back and forth a few times on my view of exactly how to classify Artifact Hub. I've also seen two different TOCs make two very different decisions on that question. So, I don't think that there's a clear or obvious answer here.

> There is little external or community resources working on the codebase at this time, and a large number of dependent consumers of the service. As such, I'd rather see this initiative considered critical infrastructure and have the CNCF/LF continue to fund and manage it as such.

One thing that I've been struggling a bit with if why we can't have both "this initiative considered critical infrastructure and have the CNCF/LF continue to fund and manage it as such" and this being an incubating project. Today we have this sort of arrangement with Artifact Hub as a sandbox project, so why does moving to incubation threaten the CNCF/LF funding or management?

**Comment by dmueller2001** [comment]
@dzolotusky As far as I have heard, there is no 'threat' to the continued funding of the CNCF-funded developers on and managing the deployment of ArtifactHub.io.  Additional investment would always be welcome to insure service levels and uptime to continue to serve the consumers of this service. 

Incubation status recognizes certain maturity levels of community contribution & engagement in the development and maintainance of project's code base as well as adoption & deployment of the codebase of a project by other organizations. 

As artifacthub "the project" has not achieved these required levels of maturity for incubation (yet). It should not be granted to  until those levels are reached. If we continue to insist on treating artifacthub as a CNCF project - it clearly has not achieved those levels of community engagement and remains a single vendor funded initiative with little external contribution growth. 

It is unfair to elevate it to incubation status when the TOC continues to require other CNCF sandbox projects to meet these requirements. This said, I do agree with the requirements currently set out for incubation status by the TOC for incubation status and would personally have a high bar on some of the requirements.

**Comment by dzolotusky** [comment]
Thanks for the clarification, @dmueller2001 

> As artifacthub "the project" has not achieved these required levels of maturity for incubation (yet). It should not be granted to until those levels are reached.

The most recent decision of the TOC has been to allow the Artifact Hub DD process to continue. I believe that we should allow the DD process to play out and only based on that DD can we decide whether or not Artifact Hub has achieved the maturity required of the Incubation level.

**Comment by TheFoxAtWork** [comment]
@dzolotusky is there a status update for this?

**Comment by dzolotusky** [comment]
> @dzolotusky is there a status update for this?

I'm currently waiting for the last adopter that I interviewed to approve my notes and then we should be ready for public comment.

**Comment by TheFoxAtWork** [comment]
Fabulous - i've moved this to the "adopter interview" area of the board. Be sure to start the thread in the TOC channel for internal review with any additional notes/comments gotchas so we can discuss/resolve (if needed) before opening public comment.

**Comment by TheFoxAtWork** [comment]
@dzolotusky tomorrow this can move to public comment

**Comment by TheFoxAtWork** [comment]
Public Comment is out: https://lists.cncf.io/g/cncf-toc/message/8623. Closing on **WEDNESDAY. MAY 15th 2024**

**Comment by dzolotusky** [comment]
It's now been 2 weeks. Let's move this to a vote.

**Pull request merged**
