### PR TITLE
wasmCloud 2022 Annual Review

### PR DESCRIPTION
**Pull request by brooksmtownsend**
This is based off of the [Sandbox Annual Review](https://github.com/cncf/toc/blob/master/process/sandbox-annual-review.md) process. 
- [x] Is your PR called: [Project name] [year] Annual Review?
- [x] Did you include a file for <year>-<project name>-annual.md?
- [x] Did you include a link to your project’s devstats page?
- [x] Did you include a link to your MAINTAINERS file?
- [x] What do you know about adoption? Is there an existing ADOPTERS file?
- [x] Did you include any previous goals?
- [x] Are your current goals listed?
- [x] Did you include requests from the CNCF?
- [x] Do you want to start the process for incubation? (This is a separate process) 
  - Noted in the annual review, we would like to start the incubation process as we meet all of the requirements.

### CODE REVIEW

**Comment by brooksmtownsend** [comment]
Original PR at #1113, accidentally closed

**Comment by Saim-Safdar** [comment]
@TheFoxAtWork we will start working from here.

**Comment by raravena80** [comment]
@Saim-Safdar checkin in here.  Were you able to complete the review? Thanks!

**Comment by raravena80** [comment]
Here's the [doc link](https://docs.google.com/document/d/1vjfPhLZVTYp3gzURciVjKsSpAQLMLcugfUl54CzmbvA/edit) to the review,

**Comment by TheFoxAtWork** [comment]
@nikhita @RichiH @cathyhongzhang please review the linked comment/recommendation from the TAG and provide concurrence/approval.

**Comment by amye** [comment]
Marking this as complete, annual reviews are no longer a requirement for sandbox. 
We'll be rolling out more efficient ways to show project health and metrics in 2024.

**Pull request merged**
