### PR TITLE
proposal: chubaofs to incubation stage

### PR DESCRIPTION
**Pull request by shuoranliu**
ChubaoFS joined CNCF as a sandbox project in Dec 2019. Now the community would like to propose ChubaoFS to the incubation stage, since it has been used in production in several notable companies, and key committers coming from diverse organizations.

Signed-off-by: Shuoran Liu <shuoranliu@gmail.com>

### CODE REVIEW

**Comment by chira001** [comment]
Hi @shuoranliu - I've sent an email enquiring about availability of the project team to present at one of the next SIG calls as a next step.   Thank you!

**Comment by shuoranliu** [comment]
Hi @chira001 - I received the email and thanks for the detailed guidance. The 4th Wednesday of Feb (24th Feb) would be great, if possible. And I'll send out the presentation slides later today. Please feel free to contact me if there's anything else required. Thanks in advance!

**Comment by caniszczyk** [comment]
Do we have any interested @cncf/toc members to sponsor this?

@resouer maybe you can help given the wider adoption in China?

**Comment by resouer** [comment]
@caniszczyk Yes, please assign it to me and I'd like to sponsor the project.

**Comment by shuoranliu** [comment]
@resouer thanks for the interest, please feel free to cantact us if anything required.

**Comment by resouer** [comment]
@shuoranliu The next step would be drafting the Due Diligence doc https://github.com/cncf/toc/blob/main/process/dd-review-template.md. An example is: https://docs.google.com/document/d/1Z6yPN9-bWeVGpMrBxXJ3NBTBYZowJ3R93wKHEVmBJ1A/edit#. SIG Storage co-chairs will come to review the project for the first round. Feel free to contact me on CNCF slack if more details are needed.

**Comment by shuoranliu** [comment]
@resouer Thanks for the guidance. I will prepare the DD draft this week.

**Comment by leonrayang** [comment]
@amye According to the suggestion of the project incubation sponsor, we will make some explanations. First of all, the name has been changed from ChubaoFS to CubeFS, please use CubeFS to publish. Second, I have changed the maintainer list during the incubation proposal period, no other changes. thank you very much.

**Comment by amye** [comment]
> @amye According to the suggestion of the project incubation sponsor, we will make some explanations. First of all, the name has been changed from ChubaoFS to CubeFS, please use CubeFS to publish. Second, I have changed the maintainer list during the incubation proposal period, no other changes. thank you very much.

Sure, we'll need changes to go to (1) maintainers.cncf.io as a pull request (2) email changes to cncf-maintainer-changes@cncf.io and we'll go from there!

**Pull request merged**
